"""LoRA-rack merge runtime — applies stacked adapters to the MLX SA3 DiT.

Strategy: **merge-at-rack-change**. The adapters (DoRA-rows format; product
name "LoRA") are merged into the DiT weights once per rack change, then
renders run at full native speed — no per-step LoRA matmuls, no edits to the
carved MLX model code. The pristine base is streamed per-key from the
on-disk npz (`models/mlx/dit_medium_f16.npz`), so nothing extra is pinned
in memory; emptying the rack restores the same keys.

The math is the EXACT upstream `LoRAParametrization.dora_forward` with
**chained** composition (the code path `load_and_apply_loras` +
`set_lora_strength` executes — the one the owner's stacking experiments
validated). Per adapter, viewed 2D as ``W ∈ R^{out × in·k}``::

    s == 0:  W' = W                      (exact short-circuit)
    else:    V  = W + (alpha/rank)·s·(B@A)
             V̂  = V / (‖V‖_row + 1e-12)
             W' = m ⊙_row V̂

Chained: adapter k's forward receives adapter k-1's OUTPUT as its "W" —
order-dependent (rack order = UI order). The alternative delta-sum
semantics (upstream ``merge_loras_into_base_model``) is deliberately NOT
implemented; ``compose_chain`` is the single seam if that ever changes.

Pinned by service/scripts/lora_merge_math_test.py against a fixture
generated by the real upstream torch code (scripts/loras/gen_dora_golden.py).

numpy for all math (golden-testable anywhere); mlx is only touched inside
merge_rack/restore_base at the ``load_weights`` boundary.
"""
from __future__ import annotations

import json
import os
import struct
import time

import numpy as np

_EPS = 1e-12

# ── safetensors reading (numpy, no torch) ─────────────────────────────────────

_DTYPES = {"F16": np.float16, "F32": np.float32, "F64": np.float64,
           "BF16": None}  # BF16 unsupported — real adapters are F16


def _read_safetensors(path):
    """-> (header dict, raw bytes offset base, file bytes)."""
    with open(path, "rb") as f:
        (n,) = struct.unpack("<Q", f.read(8))
        header = json.loads(f.read(n).decode("utf-8"))
        data = f.read()
    return header, data


def parse_adapter(path):
    """Read one adapter file -> {"targets": {mod: {A,B,m}}, "scaling", "adapter_type"}.

    - keys `<mod>.parametrizations.weight.0.{lora_A,lora_B,magnitude}`
    - all tensors upcast to fp32 (mirrors torch fp32 params <- fp16 checkpoint)
    - legacy 2D magnitude squeezed to 1D (upstream prepare_dora_state_dict)
    """
    header, data = _read_safetensors(path)
    meta = header.get("__metadata__") or {}
    cfg = {}
    if meta.get("lora_config"):
        try:
            cfg = json.loads(meta["lora_config"])
        except Exception:  # noqa: BLE001
            cfg = {}

    targets: dict = {}
    rank_seen = 0
    marker = ".parametrizations.weight.0."
    for key, info in header.items():
        if key == "__metadata__" or marker not in key:
            continue
        mod, param = key.split(marker, 1)
        if param not in ("lora_A", "lora_B", "magnitude"):
            continue
        np_dt = _DTYPES.get(info["dtype"])
        if np_dt is None:
            raise ValueError(f"unsupported tensor dtype {info['dtype']} in {path}")
        s, e = info["data_offsets"]
        arr = np.frombuffer(data[s:e], dtype=np_dt).reshape(info["shape"])
        arr = arr.astype(np.float32)
        t = targets.setdefault(mod, {})
        t["A" if param == "lora_A" else "B" if param == "lora_B" else "m"] = arr
        if param == "lora_A":
            rank_seen = arr.shape[0]

    # squeeze legacy 2D magnitudes
    for t in targets.values():
        if t.get("m") is not None and t["m"].ndim == 2:
            t["m"] = t["m"].reshape(-1)

    raw_type = str(cfg.get("adapter_type") or "dora-rows")
    adapter_type = "dora-rows" if raw_type == "dora" else raw_type
    rank = int(cfg.get("rank") or rank_seen or 1)
    alpha = float(cfg.get("alpha") or rank)
    return {"targets": targets, "scaling": alpha / rank,
            "adapter_type": adapter_type, "rank": rank}


# ── key mapping (pytorch adapter keys -> MLX DiT param keys) ──────────────────

def mod_to_mlx_key(mod: str) -> str:
    """`model.<dit-path>` -> `<dit-path>.weight` with the MLX port's renames.

    Mirrors models/defs/dit_mlx_medium.py convert_weights():
      - to_local_embed.{0,2} -> to_local_embed.seq.{0,2}
    (conv layout is handled by merge_tensor, not the key.)
    """
    m = mod
    if m.startswith("model."):
        m = m[len("model."):]
    m = m.replace(".to_local_embed.0", ".to_local_embed.seq.0")
    m = m.replace(".to_local_embed.2", ".to_local_embed.seq.2")
    if m.startswith("to_local_embed.0"):
        m = "to_local_embed.seq.0" + m[len("to_local_embed.0"):]
    if m.startswith("to_local_embed.2"):
        m = "to_local_embed.seq.2" + m[len("to_local_embed.2"):]
    return m + ".weight"


# ── the DoRA math (fp32 numpy, upstream-exact) ────────────────────────────────

def dora_rows_apply(W2d, A, B, m, scaling, s):
    """One dora-rows stage on a 2D weight. Upstream dora_forward, verbatim."""
    if s == 0.0:
        return W2d
    V = W2d + (scaling * s) * (B @ A)
    Vn = np.linalg.norm(V, axis=1, keepdims=True)
    V_hat = V / (Vn + _EPS)
    return V_hat * m[:, None]


def lora_apply(W2d, A, B, scaling, s):
    """Plain-LoRA stage (no magnitude renorm)."""
    if s == 0.0:
        return W2d
    return W2d + (scaling * s) * (B @ A)


def compose_chain(W0_2d, stages):
    """Sequential (chained) composition in rack order.

    stages: [{"type", "scaling", "strength", "A", "B", "m"}, ...]
    """
    W = np.asarray(W0_2d, dtype=np.float32)
    for st in stages:
        if st["type"] == "dora-rows":
            W = dora_rows_apply(W, st["A"], st["B"], st["m"],
                                st["scaling"], float(st["strength"]))
        elif st["type"] == "lora":
            W = lora_apply(W, st["A"], st["B"], st["scaling"], float(st["strength"]))
        else:
            raise ValueError(f"unsupported adapter type {st['type']!r}")
    return W


def merge_tensor(base, stages):
    """Apply a stage chain to one base tensor in ITS OWN layout.

    - 2D [out, in]  (Linear): math runs directly.
    - 3D [out, k, in] (MLX Conv1d layout): permuted to the torch 2D domain
      [out, in·k] — the domain the magnitudes were trained in — then back.
    Output dtype float32; caller casts to the model dtype.
    """
    base = np.asarray(base)
    if base.ndim == 2:
        return compose_chain(base.astype(np.float32), stages)
    if base.ndim == 3:
        out_f, k, in_f = base.shape
        w_torch = base.transpose(0, 2, 1).reshape(out_f, in_f * k).astype(np.float32)
        merged = compose_chain(w_torch, stages)
        return merged.reshape(out_f, in_f, k).transpose(0, 2, 1)
    raise ValueError(f"unsupported weight ndim {base.ndim}")


# ── rack identity ─────────────────────────────────────────────────────────────

def rack_signature(rack) -> str:
    """Ordered identity of a resolved rack: 'sha256:strength;...'.

    rack: [{"sha256", "strength"}, ...] — strength is the 0..N float
    (UI value / 100). Rounded to 4dp so float noise can't thrash merges.
    """
    return ";".join(f"{r['sha256']}:{float(r['strength']):.4f}" for r in rack) or "<base>"


# ── the MLX boundary ──────────────────────────────────────────────────────────

def _adapter_mlx_targets(parsed):
    """{mlx_key: (mod, stage-dict-sans-strength)} for one parsed adapter."""
    out = {}
    for mod, t in parsed["targets"].items():
        if t.get("A") is None or t.get("B") is None:
            continue
        out[mod_to_mlx_key(mod)] = (mod, {
            "type": parsed["adapter_type"], "scaling": parsed["scaling"],
            "A": t["A"], "B": t["B"], "m": t.get("m"),
        })
    return out


def merge_rack(dit_model, pristine_npz_path, rack, mx=None, batch=64):
    """Merge a resolved rack into the live MLX DiT.

    rack: [{"path", "strength", ...}, ...] in rack (UI) order; strength>0.
    Streams pristine weights per-key from the npz; applies the chained math
    per target; updates the model in batches of `batch` tensors to bound
    transient memory. Returns stats {"targets", "ms", "adapters"}.
    """
    if mx is None:
        import mlx.core as mx  # noqa: PLC0415

    t0 = time.time()
    parsed = [parse_adapter(r["path"]) for r in rack]
    per_adapter = [_adapter_mlx_targets(p) for p in parsed]

    all_keys: list = []
    seen = set()
    for pa in per_adapter:
        for k in pa:
            if k not in seen:
                seen.add(k)
                all_keys.append(k)

    npz = np.load(pristine_npz_path)
    npz_keys = set(npz.files)
    missing = [k for k in all_keys if k not in npz_keys]
    if missing:
        # Conditioner-side targets (e.g. ken-sa3's pre-`--exclude` seconds_total
        # embedder) aren't DiT params — skip them with a note. A miss on real
        # DiT paths means the wrong base model: fail loudly.
        dit_misses = [k for k in missing
                      if not k.startswith(("conditioner", "cond."))]
        if dit_misses:
            raise ValueError(
                f"{len(dit_misses)} adapter targets not found in the base model "
                f"(first: {dit_misses[0]}) — wrong base model for this LoRA?")
        print(f"[loras] skipping {len(missing)} non-DiT target(s): "
              f"{missing[:3]}", flush=True)
        all_keys = [k for k in all_keys if k in npz_keys]

    updates = []
    n_done = 0
    for key in all_keys:
        base = npz[key]
        stages = []
        for i, pa in enumerate(per_adapter):
            hit = pa.get(key)
            if hit is None:
                continue
            st = dict(hit[1])
            st["strength"] = float(rack[i]["strength"])
            stages.append(st)
        merged = merge_tensor(base, stages).astype(np.float16)
        updates.append((key, mx.array(merged)))
        n_done += 1
        if len(updates) >= batch:
            dit_model.load_weights(updates, strict=False)
            mx.eval(dit_model.parameters())
            updates = []
    if updates:
        dit_model.load_weights(updates, strict=False)
        mx.eval(dit_model.parameters())

    return {"targets": n_done, "adapters": len(rack),
            "keys": all_keys, "ms": int((time.time() - t0) * 1000)}


def restore_base(dit_model, pristine_npz_path, target_keys, mx=None, batch=64):
    """Reload the pristine values for `target_keys` (undo a previous merge)."""
    if mx is None:
        import mlx.core as mx  # noqa: PLC0415
    npz = np.load(pristine_npz_path)
    updates = []
    for key in target_keys:
        updates.append((key, mx.array(npz[key].astype(np.float16))))
        if len(updates) >= batch:
            dit_model.load_weights(updates, strict=False)
            mx.eval(dit_model.parameters())
            updates = []
    if updates:
        dit_model.load_weights(updates, strict=False)
        mx.eval(dit_model.parameters())
