#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
ENTRY="$ROOT/scripts/first-stranger/codex-native-loop.sh"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

pass=0
fail=0
ok() { pass=$((pass + 1)); printf 'ok %d - %s\n' "$pass" "$1"; }
not_ok() { fail=$((fail + 1)); printf 'not ok %d - %s\n' "$((pass + fail))" "$1" >&2; }
assert_eq() { local n="$1" w="$2" g="$3"; [ "$w" = "$g" ] && ok "$n" || not_ok "$n (want=$w got=$g)"; }
assert_match() { local n="$1" p="$2" f="$3"; rg -q -- "$p" "$f" && ok "$n" || not_ok "$n"; }
assert_no_match() { local n="$1" p="$2" f="$3"; if rg -q -- "$p" "$f"; then not_ok "$n"; else ok "$n"; fi; }

REMOTE="$TMP/remote.git"
REPO="$TMP/repo"
HOME_DIR="$TMP/automation"
WORK_ROOT="$TMP/worktrees"
STUB_STATE="$TMP/stub-state"
mkdir -p "$STUB_STATE" "$HOME_DIR"
git init --bare -q "$REMOTE"
git init -q "$REPO"
git -C "$REPO" checkout -q -b main
git -C "$REPO" config user.name "Codex Native Test"
git -C "$REPO" config user.email "codex-native@test.invalid"

mkdir -p "$REPO/docs/first-stranger-program/lanes" "$REPO/scripts/auto-loop"
printf '# fixture\n' >"$REPO/AGENTS.md"
printf '# fixture spec\n' >"$REPO/docs/first-stranger-program/SPEC.md"
printf '# FS-Z1 fixture plan\n' >"$REPO/docs/first-stranger-program/lanes/fs-z1.md"
printf '%s\n' '{"id":"FS-Z1","lane":"Z","title":"Hermetic lane","class":"cheap","status":"ready","order":1,"files":["docs/"],"acceptance":"fixture"}' >"$REPO/docs/first-stranger-program/backlog.jsonl"

cat >"$REPO/scripts/auto-loop/classify.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
jq -nc '{class:"cheap",excluded:false,excluded_paths:[],paths:["docs/generated.md"],diff_empty:false}'
EOF
cat >"$REPO/scripts/auto-loop/gate.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
jq -nc '{pass:true,class:"cheap",selftest:[],selftest_failed:0,asserts:0,steps:[{name:"fixture",ok:true}]}'
EOF
chmod +x "$REPO/scripts/auto-loop/classify.sh" "$REPO/scripts/auto-loop/gate.sh"
git -C "$REPO" add .
git -C "$REPO" commit -qm "fixture"
git -C "$REPO" remote add origin "$REMOTE"
git -C "$REPO" push -q -u origin main

CODEX_STUB="$TMP/codex"
cat >"$CODEX_STUB" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >>"$CN_STUB_STATE/codex.log"
schema=""; out=""; wt=""
args=("$@")
i=0
while [ "$i" -lt "${#args[@]}" ]; do
  arg="${args[$i]}"
  case "$arg" in
    --output-schema) i=$((i + 1)); schema="${args[$i]}" ;;
    -o|--output-last-message) i=$((i + 1)); out="${args[$i]}" ;;
    -C|--cd) i=$((i + 1)); wt="${args[$i]}" ;;
  esac
  i=$((i + 1))
done
phase="$(basename "$schema" .json)"
if [ -n "$wt" ]; then printf '%s\n' "$wt" >"$CN_STUB_STATE/worktree"; else wt="$(cat "$CN_STUB_STATE/worktree")"; fi
case "$phase" in
  plan)
    printf '%s\n' '{"id":"FS-Z1","planned":true,"gap_exists":true,"route":"safe","summary":"fixture plan is current"}' >"$out"
    ;;
  implement)
    printf '# generated by fixture\n' >"$wt/docs/generated.md"
    printf '%s\n' '{"id":"FS-Z1","ready_for_gate":true,"summary":"implemented","tests_run":["fixture"],"blockers":[]}' >"$out"
    ;;
  review)
    printf '%s\n' '{"verdict":"APPROVE","blockers":0,"reasons":[]}' >"$out"
    ;;
  *) exit 91 ;;
esac
printf '%s\n' '{"type":"thread.started","thread_id":"019f0000-0000-7000-8000-000000000001"}'
EOF
chmod +x "$CODEX_STUB"

GH_STUB="$TMP/gh"
cat >"$GH_STUB" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >>"$CN_STUB_STATE/gh.log"
if [ "${1:-}" = pr ] && [ "${2:-}" = create ]; then
  printf 'https://example.invalid/draft/1\n'
fi
EOF
chmod +x "$GH_STUB"

touch "$HOME_DIR/ARMED"
chmod 600 "$HOME_DIR/ARMED"
before="$(git -C "$REPO" status --porcelain=v1 --untracked-files=all)"
env CN_REPO="$REPO" CN_HOME="$HOME_DIR" CN_WORK_ROOT="$WORK_ROOT" \
  CN_BASE_REF=origin/main CN_PR_BASE=main CN_CODEX_BIN="$CODEX_STUB" \
  CN_GH_BIN="$GH_STUB" CN_CLASSIFY="$REPO/scripts/auto-loop/classify.sh" \
  CN_GATE="$REPO/scripts/auto-loop/gate.sh" CN_STUB_STATE="$STUB_STATE" \
  "$ENTRY" run --lane FS-Z1 >"$TMP/run.out"
after="$(git -C "$REPO" status --porcelain=v1 --untracked-files=all)"

STATE="$HOME_DIR/state/fs-z1.json"
assert_eq "fixture reaches draft-PR phase" pr-opened "$(jq -r .phase "$STATE")"
assert_eq "fixture preserves the primary checkout" "$before" "$after"
assert_match "implementation resumed the planning thread" 'exec resume .*019f0000' "$STUB_STATE/codex.log"
assert_match "agent sessions ignore user config" '--ignore-user-config' "$STUB_STATE/codex.log"
assert_match "write phases use workspace-write" 'sandbox_mode="workspace-write"' "$STUB_STATE/codex.log"
assert_match "hostile review is read-only" '-s read-only' "$STUB_STATE/codex.log"
assert_match "supervisor opens a draft PR" 'pr create --draft' "$STUB_STATE/gh.log"
assert_no_match "no GitHub merge command is reachable" '(^| )merge( |$)' "$STUB_STATE/gh.log"
local_head="$(jq -r .head_sha "$STATE")"
remote_head="$(git -C "$REPO" ls-remote origin refs/heads/codex/stranger-fs-z1 | awk '{print $1}')"
assert_eq "remote head equals exact gated head" "$local_head" "$remote_head"
assert_eq "state remains private" 600 "$(stat -f '%Lp' "$STATE")"

if [ "$fail" -ne 0 ]; then
  printf '%d integration test(s) failed; %d passed\n' "$fail" "$pass" >&2
  exit 1
fi
printf '%d integration tests passed\n' "$pass"
