#!/usr/bin/env python3
"""Generate docs/FEATURE_AUDIT.md — the present-tense DAW-parity scoreboard.

Renders ONLY from committed inputs, so the scoreboard is regenerable (and checkable)
without a binary:

  scripts/daw-conformance/verdicts.json        normalized outcome of the last conformance
                                               run (conformance.py --write-verdicts; a
                                               plain native-lane run FAILS if it disagrees)
  docs/reality-pack/mosh_daw_eval_suite.csv    the scenario→row fan-out
  docs/auto-loop/backlog.jsonl                 the parity backlog (single source of truth —
                                               the old hardcoded BACKLOG list is gone)
  coverage_check.compute()                     static command-surface coverage ledger

`--check` regenerates in-memory and diffs against the committed file: a stale scoreboard
fails the CHEAP gate lane. That closes the staleness class where FEATURE_AUDIT still
showed Export=15 gaps three weeks after export range/tail shipped.
"""
import argparse
import csv
import json
import sys
from pathlib import Path

import coverage_check

REPO = Path(__file__).resolve().parents[2]
SELF = Path(__file__).resolve().parent
EVAL_CSV = REPO / "docs" / "reality-pack" / "mosh_daw_eval_suite.csv"
VERDICTS = SELF / "verdicts.json"
BACKLOG = REPO / "docs" / "auto-loop" / "backlog.jsonl"
OUT = REPO / "docs" / "FEATURE_AUDIT.md"

STATUS_LABEL = {"pass": "✅ pass", "fail": "❌ FAIL", "gap": "🟡 gap",
                "hardware": "🔌 hardware", "out-of-scope": "— out-of-scope"}


def load_inputs():
    verdicts = json.loads(VERDICTS.read_text())
    rows = list(csv.DictReader(EVAL_CSV.open()))
    backlog = []
    for line in BACKLOG.read_text().splitlines():
        line = line.strip()
        if line:
            try:
                backlog.append(json.loads(line))
            except json.JSONDecodeError:
                pass  # model_lint.py owns backlog validity
    return verdicts, rows, backlog


def render():
    verdicts, rows, backlog = load_inputs()
    vmap = {(v["area"], v["action"]): v for v in verdicts}

    # Fan the family verdicts back over the eval rows (the padded legacy CSV).
    per_id = []
    for r in rows:
        v = vmap.get((r["area"], r["user_action"]))
        per_id.append({"area": r["area"], "status": v["status"] if v else "fail"})
    by_status = {}
    by_area = {}
    for it in per_id:
        by_status[it["status"]] = by_status.get(it["status"], 0) + 1
        by_area.setdefault(it["area"], {}).setdefault(it["status"], 0)
        by_area[it["area"]][it["status"]] += 1
    in_scope = len(per_id) - by_status.get("out-of-scope", 0)

    csv_verdicts = [v for v in verdicts if v["area"] != "Post-pack"]
    post_pack = [v for v in verdicts if v["area"] == "Post-pack"]
    parity_items = [b for b in backlog if b.get("id", "").startswith("G")]
    open_items = [b for b in parity_items if b.get("status") != "done"]
    done_items = [b for b in parity_items if b.get("status") == "done"]
    cov = coverage_check.compute()
    n_cov = sum(1 for s in cov["commands"].values() if s)

    L = []
    L.append("# Mosh — DAW Parity Scoreboard")
    L.append("")
    L.append("_Generated by `scripts/daw-conformance/scoreboard.py` from the committed verdicts "
             "of the last live conformance run (`conformance.py --write-verdicts`), the "
             "reality-pack eval suite, and the parity backlog. `scoreboard.py --check` fails "
             "the cheap gate lane when this file goes stale._")
    L.append("")
    L.append("> **This supersedes the 2026-06-09 baseline audit.** That audit's JSON "
             "(`167 missing / 24 shipped`) was a point-in-time snapshot; ~20 feature waves and "
             "subsequent work landed on top of it, so it cannot be read as current. This page is "
             "regenerated from the gathered reality-pack eval suite replayed through the **real "
             "command surface** — it reflects what the code does *now*. The archived baseline "
             "lives in `docs/archive/feature-audit-2026-06-09/`.")
    L.append("")
    L.append("## Headline")
    L.append("")
    n_families = len([v for v in csv_verdicts if v["status"] != "out-of-scope"])
    L.append(f"- **{len([v for v in csv_verdicts if v['status'] == 'pass'])} / {n_families} "
             f"in-scope scenario families pass** (plus {len(post_pack)} post-pack families), "
             f"proven headless (state / audio / undo asserted).")
    L.append(f"- Row view (the padded legacy CSV): {by_status.get('pass', 0)} / {in_scope} in-scope "
             f"eval rows pass — the historical headline metric; each family fans out to ~8 "
             f"near-duplicate rows, so the FAMILY count above is the honest one.")
    L.append(f"- **{by_status.get('gap', 0)} gap** rows — tracked, attributed backlog items.")
    L.append(f"- **{by_status.get('hardware', 0)} hardware** rows — need a live device "
             f"(Phase-1 hardware pass).")
    L.append(f"- **{by_status.get('out-of-scope', 0)} out-of-scope** rows — Monster / Arena / "
             "Collaboration (outside the conventional-parity pass).")
    L.append(f"- Command-surface coverage: **{n_cov} / {cov['total']}** dispatch commands "
             f"exercised by ≥1 test surface; {len(cov['waived'])} waived (reasoned, expiring — "
             f"see `scripts/daw-conformance/coverage_waivers.json`); "
             f"{len(cov['uncovered'])} uncovered.")
    L.append("")

    L.append("## Parity by area (eval suite)")
    L.append("")
    L.append("| Area | pass | gap | hardware | out-of-scope |")
    L.append("|---|---|---|---|---|")
    for area in sorted(by_area):
        c = by_area[area]
        L.append(f"| {area} | {c.get('pass', 0)} | {c.get('gap', 0)} | "
                 f"{c.get('hardware', 0)} | {c.get('out-of-scope', 0)} |")
    L.append("")

    L.append("## Scenario verdicts")
    L.append("")
    L.append("| Area | Scenario | Status | Invariants | Notes |")
    L.append("|---|---|---|---|---|")
    for v in csv_verdicts:
        note = v.get("note", "")
        if v.get("backlog_ref"):
            note = f"**{v['backlog_ref']}** — {note}"
        inv = ",".join(str(i) for i in v.get("invariants", [])) or "—"
        L.append(f"| {v['area']} | {v['action']} | {STATUS_LABEL.get(v['status'], v['status'])} "
                 f"| {inv} | {note} |")
    L.append("")

    if post_pack:
        L.append("## Post-pack families (capabilities shipped after the reality pack was gathered)")
        L.append("")
        L.append("| Family | Status | Invariants | Notes |")
        L.append("|---|---|---|---|")
        for v in post_pack:
            inv = ",".join(str(i) for i in v.get("invariants", [])) or "—"
            L.append(f"| {v['action']} | {STATUS_LABEL.get(v['status'], v['status'])} "
                     f"| {inv} | {v.get('note', '')} |")
        L.append("")

    L.append("## Conventional-parity backlog (drives the auto-loop)")
    L.append("")
    L.append("Read live from `docs/auto-loop/backlog.jsonl` (the single source of truth — items "
             "are G-prefixed). `cheap` = UI/agent wiring (auto-mergeable); `native` = "
             "MoshOps/engine.")
    L.append("")
    if open_items:
        L.append("| id | status | class | size | Gap |")
        L.append("|---|---|---|---|---|")
        for b in sorted(open_items, key=lambda b: b.get("order", 0)):
            L.append(f"| {b['id']} | {b.get('status', '')} | {b.get('class', '')} | "
                     f"{b.get('size', '')} | {b.get('title', '')} |")
    else:
        L.append("_No open parity items._")
    L.append("")
    L.append(f"_{len(done_items)} parity items landed and reconciled "
             f"({', '.join(b['id'] for b in sorted(done_items, key=lambda b: b.get('order', 0)))}) "
             f"— evidence lives in their backlog notes._")
    L.append("")

    L.append("## How this stays honest")
    L.append("")
    L.append("- `conformance.py` runs in the native gate and FAILS on any in-scope regression "
             "**or any drift from the committed `verdicts.json`** — a behavior change must land "
             "its verdict flip (and this regenerated scoreboard) in the same PR.")
    L.append("- `scoreboard.py --check`, `model_lint.py`, and `coverage_check.py` run in the "
             "cheap gate lane: a stale scoreboard, an unmapped eval scenario, a gap pointing at "
             "a done backlog item, or an untested dispatch command each fail the gate on their "
             "own — no binary needed.")
    L.append("- Audio/undo claims are asserted against real rendered WAVs and the real "
             "`snapshot()` (via the `__snapshot` run-script directive) — not against command "
             "return codes.")
    L.append("- Hardware-only behavior (mic capture, live meters, MIDI input, multi-out, loop "
             "playback) is confirmed in the Phase-1 hardware pass — see `docs/VERIFICATION.md`.")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description="DAW-parity scoreboard generator")
    ap.add_argument("--check", action="store_true",
                    help="regenerate in-memory and fail if docs/FEATURE_AUDIT.md is stale")
    args = ap.parse_args()

    content = render()
    if args.check:
        committed = OUT.read_text() if OUT.exists() else ""
        if committed != content:
            print("scoreboard: STALE — docs/FEATURE_AUDIT.md does not match its committed inputs.")
            print("  regenerate with: python3 scripts/daw-conformance/scoreboard.py  (and commit)")
            import difflib
            diff = list(difflib.unified_diff(committed.splitlines(), content.splitlines(),
                                             "committed", "regenerated", lineterm="", n=0))
            for line in diff[:40]:
                print(f"  {line}")
            return 1
        print("scoreboard: fresh (matches committed inputs)")
        return 0

    OUT.write_text(content)
    print(f"wrote {OUT}  ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
