// Node-side persistence for the technique-card knowledge base. The JSONL at
// eval/knowledge/cards.jsonl is the single source of truth (all statuses + evidence,
// what the future YouTube miner also appends to). The product bundle can't read files
// at runtime, so writeCardsData() bakes the VALIDATED subset into the browser-safe
// src/agent/knowledge/cards.data.ts (like build_colorrack bakes COLORRACK_DATA).
// Node-only (node:fs) — kept in scripts/, never imported by the product.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { type TechniqueCard, isShippable } from "../src/agent/knowledge/card";

const UI_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const REPO = resolve(UI_ROOT, "..");
export const STORE_PATH = resolve(REPO, "eval/knowledge/cards.jsonl");
const CARDS_DATA_PATH = resolve(UI_ROOT, "src/agent/knowledge/cards.data.ts");

export function loadCards(path = STORE_PATH): TechniqueCard[] {
  if (!existsSync(path)) return [];
  return readFileSync(path, "utf8")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => JSON.parse(l) as TechniqueCard);
}

export function saveCards(cards: TechniqueCard[], path = STORE_PATH): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, cards.map((c) => JSON.stringify(c)).join("\n") + (cards.length ? "\n" : ""));
}

/** Merge cards into the store by id (incoming wins — a re-validation updates evidence). */
export function upsertCards(incoming: TechniqueCard[], path = STORE_PATH): TechniqueCard[] {
  const byId = new Map(loadCards(path).map((c) => [c.id, c]));
  for (const c of incoming) byId.set(c.id, c);
  const merged = [...byId.values()];
  saveCards(merged, path);
  return merged;
}

/** Regenerate the product's baked shippable-card module from the store. Returns the
 *  count of cards written (validated prompt + conformant/preferred recipe cards). */
export function writeCardsData(cards = loadCards()): number {
  const validated = cards.filter(isShippable);
  const body =
    "// GENERATED by `npm run flywheel` from eval/knowledge/cards.jsonl — do not edit by hand.\n" +
    "// The validated technique cards the product bundle ships, retrieved + injected at\n" +
    "// inference (retrieve.ts). Regenerate by running the flywheel after it validates cards.\n" +
    'import type { TechniqueCard } from "./card";\n\n' +
    `export const VALIDATED_CARDS: TechniqueCard[] = ${JSON.stringify(validated, null, 2)};\n`;
  writeFileSync(CARDS_DATA_PATH, body);
  return validated.length;
}
