// ============================================================================
// ARENA VISION PANEL — grounded model review of REAL rendered screenshots.
//
// The runner (run.mjs) captures interaction-state screenshots; this sends them to
// every VISION-CAPABLE provider through the existing spend-capped /api/arena/chat
// proxy (multimodal content arrays pass through verbatim; keys stay server-side)
// and collects STRICT-JSON findings + ideas per model for the director (Fable) to
// triage. Models stop imagining designs and start verifying pixels.
//
// Usage:
//   node tools/verify/vision.mjs --probe        # capability-test each provider (1 tiny image)
//   node tools/verify/vision.mjs                # review all candidates in .verify/report.json
//   node tools/verify/vision.mjs --providers=anthropic,openai
// Output: .verify/<seed>/findings-<provider>.json + .verify/findings-summary.json
// ============================================================================
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const arenaDir = resolve(here, "../..");
const OUT = resolve(arenaDir, ".verify");
const BASE = "http://localhost:5273";

// 16x16 solid #e02020 — generated by Playwright (1x1 probes are ambiguous after model-side
// rescaling, and xai rejects images under 8px)
const RED_PX = readFileSync(resolve(OUT, "probe-red.png")).toString("base64");

const argProviders = (process.argv.find((a) => a.startsWith("--providers=")) || "").split("=")[1];
const PROBE_ONLY = process.argv.includes("--probe");

async function chat(provider, content) {
  const r = await fetch(`${BASE}/api/arena/chat`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ provider, messages: [{ role: "user", content }] }),
  });
  const j = await r.json().catch(() => ({}));
  if (!r.ok) throw new Error(j.error || `HTTP ${r.status}`);
  return j;
}

function img(b64) {
  return { type: "image_url", image_url: { url: `data:image/png;base64,${b64}` } };
}
function parseJson(text) {
  let t = String(text || "").trim();
  if (t.startsWith("```")) t = t.replace(/^```[a-zA-Z]*\s*\n?/, "").replace(/\n?```\s*$/, "");
  const start = t.indexOf("{");
  if (start > 0) t = t.slice(start);
  return JSON.parse(t);
}

async function probe(providers) {
  const ok = [];
  for (const p of providers) {
    process.stdout.write(`  probe ${p} … `);
    try {
      const j = await chat(p, [
        { type: "text", text: 'One word: what color is this image? Reply as JSON {"color":"..."}' },
        img(RED_PX),
      ]);
      const txt = (j.content || j.choices?.[0]?.message?.content || JSON.stringify(j)).toLowerCase();
      const sees = txt.includes("red");
      console.log(sees ? "VISION OK" : `no ("${txt.slice(0, 60)}")`);
      if (sees) ok.push(p);
    } catch (e) {
      console.log(`FAIL — ${String(e.message).slice(0, 80)}`);
    }
  }
  return ok;
}

const BRIEF = `You are reviewing REAL screenshots of design mockups for MOSH, a professional DAW ("the iPhone of DAWs").
Identity: near-black obsidian dark theme with metallic/volumetric depth (never flat gray); sacred lime #ccff36 used SPARINGLY (playhead, commit, live accents only); desaturated per-track hues (amber/violet/teal/pink); mono micro-caps labels; professional precision-instrument register — never toy/video-game; PROGRESSIVE DISCLOSURE (info/controls surface only when the user seeks them); generous calm negative space at the periphery.
The two surfaces are ONE product: a desktop shell and an iPhone companion remote that share an arrangement-navigator component (song sections with hue cap-ticks and top-edge labels, a lime playhead, collaborator beads — on DESKTOP the beads ride the lower half to clear the labels; on PHONE labels are hidden so the beads recentre vertically; both are deliberate).

GROUND TRUTH (do not misidentify these):
- MOSHI is a LIVING CREATURE — a real-time-rendered blob character with eyes, the product's agent embodiment. He sits ON the prompt bar and IS the talk button (hold him to talk; a lime line lights under the bar while he listens). He is a character, never a data visualization. Judge his integration, visibility, and how inviting he is to touch.
- The lime rectangle in the desktop navigator is the draggable VIEWPORT WINDOW (frames the zoomed slice of the song) — deliberate.
- The grid is INVISIBLE at rest by doctrine; it reveals near the cursor, fully during drags. The thin tick inside a dragged clip is its musical ANCHOR (downbeat) — it lands on the glowing bar line while the clip edge sits slightly early (a pickup, preserved on purpose).
- With ⌘ held the grid bows away from the cursor ("gooey") to show snapping is OFF — deliberate.
- On the companion, KEEP/REDO rest DIMMED (nothing to judge yet) and light up only when a take verdict is pending — deliberate progressive disclosure of state.

You receive FULL-FRAME state shots first, then labeled CLOSE-UPS at 3× so you can actually inspect the components. Report ONLY what you can see in the pixels; anchor each finding to the image where you see it.
Return STRICT JSON only:
{"findings":[{"component":"which image/component","what":"…","why":"…","severity":1,"fix":"concrete, small, CSS/layout-level suggestion"}],"ideas":["…"]}
Max 6 findings — real visual defects or quality gaps you can point at (severity 3 = breaks the design intent, 1 = polish). Max 3 ideas. No praise, no filler, no rewrites.`;

// intent labels for the 3× close-ups — tell the model what it's looking at and what to judge
const CU_LABELS = {
  "moshi-on-bar-rest": "CLOSE-UP 3× — MOSHI AT REST on the floating prompt bar (desktop). A living creature perched on / spilling over the bar. Judge: inviting? cleanly integrated with the pill? visible enough against the obsidian?",
  "moshi-on-bar-talk": "CLOSE-UP 3× — MOSHI DURING HOLD-TO-TALK: he squashes slightly, listens (eyes to you), the lime line lights along the bar, placeholder reads 'listening…'. Judge the state feedback.",
  "navigator": "CLOSE-UP 3× — the shared ARRANGEMENT NAVIGATOR (desktop form): section blocks with hue cap-ticks + top-edge micro-caps labels, lime playhead + notch, collaborator beads (initials, status ring) riding the LOWER half, the lime viewport window.",
  "dock-tabs": "CLOSE-UP 3× — side-panel dock pull-tabs (SAMPLES/FILES) living in the calm peripheral margin, iridescent 1px rims.",
  "lane-hover": "CLOSE-UP 3× — a HOVERED track lane: the color rail bar swells + glows, the track name surfaces beside it, arm/M/S controls appear on the LEFT. At rest none of this is visible (progressive disclosure).",
  "clip-well": "CLOSE-UP 3× — an anodized clip well: waveform in the track hue over a cool metal well with a machined 1px bevel.",
  "drag-snap-emphasis": "CLOSE-UP 3× — MID-DRAG: the snapped bar line glows lime; the thin bright tick INSIDE the clip is its musical anchor (downbeat) sitting exactly on the line while the clip's left edge sits slightly before it (pickup preserved — deliberate).",
  "meta-goo-detail": "CLOSE-UP 3× — ⌘ HELD: snapping disabled, grid lines bow away from the cursor (gooey). Deliberate 'ignoring the grid' feedback. Judge the effect's quality, not its existence.",
  "mercury-playhead": "CLOSE-UP 3× — the playhead swept over a clip: a 'gooey mercury' energy lens pushes glowing light through the waveform where the playhead crosses it (the waveform bulges + lights lime→track-hue), and the clip lifts subtly. Judge whether this reads as premium/liquid and alive, not gimmicky.",
  "moshi-rest": "CLOSE-UP 3× — MOSHI AT REST on the companion (the talk button; a living creature, refined render register). Judge: inviting? well-sized for a thumb? visible?",
  "moshi-talk": "CLOSE-UP 3× — companion MOSHI DURING HOLD-TO-TALK: listening state, the line under him lights lime.",
  "glance-header": "CLOSE-UP 3× — the quiet glance header: song metadata + demoted bars·beats readout (deliberately secondary).",
  "nav-hero": "CLOSE-UP 3× — the arrangement navigator in PHONE-HERO form: bold lime fill, no labels, chunkier beads (same component as desktop).",
  "deck-rest": "CLOSE-UP 3× — the deck AT REST: transport strip + KEEP/REDO deliberately DIMMED (no take to judge yet — progressive disclosure of state).",
  "rec-armed": "CLOSE-UP 3× — REC ARMED/RECORDING: red tint + dot, take number riding the key.",
  "deck-pending": "CLOSE-UP 3× — VERDICT PENDING: KEEP/REDO at full strength, KEEP's lime ring pulsing gently. REDO is wider because it's hit most.",
  "keep-flash": "CLOSE-UP 3× — the moment KEEP commits (lime flash).",
};

async function review(providers) {
  const report = JSON.parse(readFileSync(resolve(OUT, "report.json"), "utf8"));
  const summary = [];
  for (const cand of report) {
    // full-frame states for composition (3) + every labeled close-up for component detail
    const shots = cand.screenshots.filter(existsSync).slice(0, 3);
    const closeups = (cand.closeups || []).filter(existsSync);
    if (!shots.length && !closeups.length) continue;
    console.log(`\n── vision review: ${cand.title} (${shots.length} fulls + ${closeups.length} close-ups × ${providers.length} models) ──`);
    const content = [
      { type: "text", text: `${BRIEF}\n\nCANDIDATE SPEC: ${cand.title} [${cand.target}]` },
      ...shots.flatMap((p) => [
        { type: "text", text: `FULL FRAME · STATE: ${basename(p).replace(/^\d+-|\.png$/g, "")}` },
        img(readFileSync(p).toString("base64")),
      ]),
      ...closeups.flatMap((p) => {
        const key = basename(p).replace(/^cu-|\.png$/g, "");
        return [
          { type: "text", text: CU_LABELS[key] || `CLOSE-UP 3× — ${key}` },
          img(readFileSync(p).toString("base64")),
        ];
      }),
    ];
    for (const p of providers) {
      process.stdout.write(`  ${p} … `);
      try {
        const j = await chat(p, content);
        const raw = j.content || j.choices?.[0]?.message?.content || "";
        const parsed = parseJson(raw);
        const out = { provider: p, model: j.model, costUsd: j.costUsd, ...parsed };
        writeFileSync(resolve(OUT, cand.seed, `findings-${p}.json`), JSON.stringify(out, null, 2));
        summary.push({ candidate: cand.seed, provider: p, findings: (parsed.findings || []).length, ideas: (parsed.ideas || []).length });
        console.log(`${(parsed.findings || []).length} findings · ${(parsed.ideas || []).length} ideas`);
      } catch (e) {
        summary.push({ candidate: cand.seed, provider: p, error: String(e.message).slice(0, 120) });
        console.log(`FAIL — ${String(e.message).slice(0, 80)}`);
      }
    }
  }
  writeFileSync(resolve(OUT, "findings-summary.json"), JSON.stringify(summary, null, 2));
  console.log("\nwrote .verify/findings-summary.json");
}

async function main() {
  const all = argProviders
    ? argProviders.split(",")
    : (await (await fetch(`${BASE}/api/arena/providers`)).json()).providers.map((p) => p.id);
  console.log("capability probe:");
  const visionOk = await probe(all);
  console.log(`vision-capable: [${visionOk.join(", ")}]`);
  if (PROBE_ONLY || !visionOk.length) return;
  await review(visionOk);
}
main().catch((e) => { console.error(e); process.exit(2); });
