#!/usr/bin/env python3
"""Training journal — the owner's ask: "saving all of these artifacts in a well
organized way so that I can easily go through them at a later point just to reflect
on the arc of the training process."

Builds entirely from the label ledger (+ the hand-written round changelog):
  ~/mosh-beats/journal/index.html   — chronological rounds, keep-rates, his notes
                                      VERBATIM beside playable beats, top picks,
                                      late annotations, what changed each round
  docs/TRAINING_JOURNAL.md          — compact markdown twin (committed)

    python3 scripts/verify-hardware/build_journal.py
"""
from __future__ import annotations

import html
import json
import os
from pathlib import Path

BEATS = Path(os.path.expanduser("~/mosh-beats"))
LEDGER = BEATS / "labels" / "labels.jsonl"
HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
CHANGELOG = REPO / "docs" / "bench" / "ROUND_CHANGELOG.md"
OUT_HTML = BEATS / "journal" / "index.html"
OUT_MD = REPO / "docs" / "TRAINING_JOURNAL.md"

ROUND_META = {
    "r1": ("Round 1 — first audition", "owner-dna/v1", "star"),
    "r2": ("Round 2 — 808 register fix", "owner-dna", "star"),
    "r3ab": ("Round 3 — pitch-truth A/B", "owner-dna-v3", "pref"),
    "r4ab": ("Round 4 — tiling A/B", "owner-dna-v4", "pref"),
}


def load_changelog() -> dict:
    """'## <round>' sections of ROUND_CHANGELOG.md → text."""
    out = {}
    if CHANGELOG.is_file():
        cur = None
        for line in CHANGELOG.read_text().splitlines():
            if line.startswith("## "):
                cur = line[3:].strip()
                out[cur] = []
            elif cur:
                out[cur].append(line)
    return {k: "\n".join(v).strip() for k, v in out.items()}


def rounds_from_ledger() -> list:
    rows = [json.loads(l) for l in LEDGER.read_text().splitlines() if l.strip()]
    order: list = []
    by_round: dict = {}
    for r in rows:
        rd = r["round"]
        if rd not in by_round:
            by_round[rd] = []
            order.append(rd)
        by_round[rd].append(r)
    return [(rd, by_round[rd]) for rd in order]


def _beat_dir(rd: str) -> str:
    return ROUND_META.get(rd, (None, rd, None))[1]


def _round_title(rd: str) -> str:
    return ROUND_META.get(rd, (rd.replace("pack-", "Taste Pack "), None, None))[0]


def build() -> None:
    changelog = load_changelog()
    rounds = rounds_from_ledger()
    h = ["<meta charset='utf-8'><title>Mosh Training Journal</title><style>",
         "body{background:#101014;color:#e8e6df;font:14px/1.6 -apple-system,sans-serif;"
         "max-width:900px;margin:0 auto;padding:24px 16px 80px}",
         "h1{font-size:22px} h2{font-size:17px;margin:34px 0 4px;color:#ffd23f}",
         ".meta{color:#9a97a6;font-size:12.5px;margin-bottom:10px}",
         ".beat{background:#191921;border:1px solid #2a2a36;border-radius:8px;"
         "padding:8px 12px;margin:8px 0}",
         ".keep{border-left:3px solid #6fe0a8}.kill{border-left:3px solid #ff6b6b}",
         ".top{border-left:3px solid #ffd23f;background:#22201a}",
         ".note{color:#cfcabf;font-style:italic;font-size:13px;margin-top:4px}",
         ".late{color:#ffd23f;font-size:12.5px;margin-top:4px}",
         ".chg{background:#15151c;border:1px dashed #2a2a36;border-radius:8px;"
         "padding:8px 12px;color:#9a97a6;font-size:12.5px;white-space:pre-wrap}",
         "audio{width:100%;height:30px;margin-top:6px}</style>",
         "<h1>Mosh Training Journal</h1>",
         "<div class='meta'>The arc of the taste-training process — every rated beat, "
         "your words verbatim, and what changed in between. Regenerated each round.</div>"]
    md = ["# Mosh Training Journal", "",
          "*Generated by build_journal.py from the label ledger — regenerate, don't edit.*", ""]

    for rd, rows in rounds:
        rated = [r for r in rows if r.get("value")]
        keeps = [r for r in rated if r.get("value") == "keep"]
        kind = rows[0].get("kind")
        if kind == "keep":
            stat = f"{len(keeps)}/{len(rated)} kept ({int(100 * len(keeps) / max(1, len(rated)))}%)"
        elif kind == "pref":
            stat = f"{sum(1 for r in rated if str(r['value']).startswith(rd[:2]))}/{len(rated)} preferred the new pipeline"
        else:
            vals = [int(r["value"]) for r in rated if str(r.get("value", "")).isdigit()]
            stat = f"stars: {vals}"
        title = _round_title(rd)
        h.append(f"<h2>{html.escape(title)}</h2><div class='meta'>{stat}</div>")
        md += [f"## {title}", "", f"- **{stat}**"]
        if rd in changelog:
            h.append(f"<div class='chg'>{html.escape(changelog[rd])}</div>")
            md += ["", "What changed before this round:", "", changelog[rd]]
        bdir = _beat_dir(rd)
        for r in rows:
            cls = "top" if r.get("topPick") else (r.get("value") if kind == "keep" else "")
            label = r["file"]
            badge = " ★ TOP PICK" if r.get("topPick") else ""
            verdict = f" — {r.get('value', '')}" if kind == "keep" else f" — {r.get('value', '')}"
            h.append(f"<div class='beat {cls}'><b>{html.escape(label)}</b>{badge}{verdict}")
            src = f"../{bdir}/{label}"
            h.append(f"<audio controls preload='none' src='{html.escape(src)}'></audio>")
            if r.get("chips"):
                h.append(f"<div class='meta'>chips: {', '.join(r['chips'])}</div>")
            if r.get("notes"):
                h.append(f"<div class='note'>“{html.escape(r['notes'])}”</div>")
            for ln in r.get("lateNotes", []):
                h.append(f"<div class='late'>later: {html.escape(ln)}</div>")
            h.append("</div>")
            note_bits = []
            if r.get("topPick"):
                note_bits.append("★ TOP PICK")
            if r.get("notes"):
                note_bits.append(f"“{r['notes']}”")
            for ln in r.get("lateNotes", []):
                note_bits.append(f"(later) {ln}")
            md.append(f"- `{label}` {r.get('value', '')}"
                      + (" — " + " · ".join(note_bits) if note_bits else ""))
        md.append("")

    OUT_HTML.parent.mkdir(parents=True, exist_ok=True)
    OUT_HTML.write_text("\n".join(h))
    OUT_MD.write_text("\n".join(md) + "\n")
    print(f"journal → {OUT_HTML}\nmarkdown twin → {OUT_MD}")


if __name__ == "__main__":
    build()
