// Live 12.4's track-header Colors radio group: all 70 named swatches, in the AX
// order (.cache/live-ref/ax/ctx-header.json's AXRadioButton descs, row-major).
// The hexes are MEASURED — sampled from the extraction proof shot (ctx-header.png)
// at each swatch's centre on 2026-08-07, per the program's observed-not-copied rule.
// Mosh's set_track_color takes a free "#rrggbb", so the mapping is 1:1 — no palette
// reduction was needed.

export const LIVE_TRACK_COLORS: { name: string; hex: string }[] = [
  { name: "Salmon", hex: "#f099a7" },
  { name: "Frank Orange", hex: "#f2a948" },
  { name: "Dirty Gold", hex: "#c49b40" },
  { name: "Lemonade", hex: "#f7f48d" },
  { name: "Lime", hex: "#cbf94f" },
  { name: "Highlighter Green", hex: "#77fb58" },
  { name: "Bianchi", hex: "#79fbaf" },
  { name: "Turquoise", hex: "#8dfce8" },
  { name: "Sky Blue", hex: "#97c3fa" },
  { name: "Sapphire", hex: "#5e7fdd" },
  { name: "Periwinkle", hex: "#96a6f9" },
  { name: "Orchid", hex: "#ca72de" },
  { name: "Magenta", hex: "#d45d9e" },
  { name: "White", hex: "#ffffff" },
  { name: "Fire Hydrant Red", hex: "#eb4a41" },
  { name: "Tangerine", hex: "#e5742e" },
  { name: "Sand", hex: "#937451" },
  { name: "Sunshine Yellow", hex: "#fcf15e" },
  { name: "Terminal Green", hex: "#a5fc7c" },
  { name: "Forest", hex: "#67c039" },
  { name: "Tiffany Blue", hex: "#56bcaf" },
  { name: "Cyan", hex: "#6de6fc" },
  { name: "Cerulean", hex: "#4ba1e8" },
  { name: "United Nations Blue", hex: "#367bbb" },
  { name: "Amethyst", hex: "#836ddd" },
  { name: "Iris", hex: "#ad7ac1" },
  { name: "Flamingo", hex: "#eb4cce" },
  { name: "Aluminum", hex: "#d0d0d0" },
  { name: "Terracotta", hex: "#d36e60" },
  { name: "Light Salmon", hex: "#f2a77c" },
  { name: "Whiskey", hex: "#cdae79" },
  { name: "Canary", hex: "#f0feb7" },
  { name: "Primrose", hex: "#d5e3a0" },
  { name: "Wild Willow", hex: "#becf7f" },
  { name: "Dark Sea Green", hex: "#a3c392" },
  { name: "Honeydew", hex: "#dcfce3" },
  { name: "Pale Turquoise", hex: "#d4f0f7" },
  // Live's palette repeats two names (Periwinkle ×2, Sapphire ×2) — exact names
  // kept; the menu keys on name+index.
  { name: "Periwinkle", hex: "#bbc1e0" },
  { name: "Fog", hex: "#cabce1" },
  { name: "Dull Lavender", hex: "#aa99e0" },
  { name: "Whisper", hex: "#e3dce1" },
  { name: "Silver Chalice", hex: "#a9a9a9" },
  { name: "Dusty Pink", hex: "#be948d" },
  { name: "Barley Corn", hex: "#af845d" },
  { name: "Pale Oyster", hex: "#95846d" },
  { name: "Dark Khaki", hex: "#beba74" },
  { name: "Pistachio", hex: "#abbd3b" },
  { name: "Dollar Bill", hex: "#88af5a" },
  { name: "Neptune", hex: "#94c0ba" },
  { name: "Nepal", hex: "#a0b2c2" },
  { name: "Polo Blue", hex: "#8ba4bf" },
  { name: "Vista Blue", hex: "#8693c7" },
  { name: "Amethyst Smoke", hex: "#a296b3" },
  { name: "Lilac", hex: "#baa0bc" },
  { name: "Turkish Rose", hex: "#b27595" },
  { name: "Steel", hex: "#7b7b7b" },
  { name: "Medium Carmine", hex: "#a13d38" },
  { name: "Red Ochre", hex: "#9e5639" },
  { name: "Coffee", hex: "#6d5043" },
  { name: "Durian Yellow", hex: "#d7c440" },
  { name: "Pomelo Green", hex: "#889637" },
  { name: "Apple", hex: "#669d42" },
  { name: "Aquamarine", hex: "#469a8e" },
  { name: "Sea Blue", hex: "#356281" },
  { name: "Cosmic Cobalt", hex: "#1f2e90" },
  { name: "Sapphire", hex: "#37519d" },
  { name: "Plump Purple", hex: "#5e4ca7" },
  { name: "Purpureus", hex: "#9850a8" },
  { name: "Fuchsia Rose", hex: "#bc3d6d" },
  { name: "Eclipse", hex: "#3c3c3c" },
];
