#!/usr/bin/env bash
# status.sh — owner-blocker dashboard for the First-Stranger loop.
#
# Read-only. Regenerates docs/first-stranger-program/STATUS.md from:
#   - the program backlog (lane status: ready / blocked / awaiting-owner / done / …)
#   - the outstanding owner critical-path blockers (O1–O6 + hardware), derived from
#     each blocked lane's `blockedOn` field
#   - the open `needs-owner-merge` PRs the loop has handed to the owner (via gh)
#
# Run at the end of each stranger-loop cycle, or any time:  bash scripts/first-stranger/status.sh
# Bash 3.2 compatible. Never mutates anything but STATUS.md.
set -uo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
PROG="$ROOT/docs/first-stranger-program"
BL="${AL_BACKLOG_JSONL:-$PROG/backlog.jsonl}"
OUT="$PROG/STATUS.md"
NOW="$(date '+%Y-%m-%d %H:%M:%S %Z')"

[ -f "$BL" ] || { echo "status.sh: no backlog at $BL" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "status.sh: jq required" >&2; exit 1; }

_all() { grep -v '^[[:space:]]*$' "$BL" 2>/dev/null | jq -sc '.'; }

# One markdown table row per lane in a given status.
_rows() {  # <status>
  _all | jq -r --arg s "$1" '
    map(select(.status==$s)) | sort_by(.order)
    | .[] | "| \(.id) | \(.lane // "-") | \(.title) | \(.class // "-") | \(.blockedOn // "-") |"'
}
_count() { _all | jq -r --arg s "$1" 'map(select(.status==$s)) | length'; }

# Owner critical-path descriptions (spec §3). Static text; the loop can't know if the
# owner has cleared them — this is the reminder surface. The "blocks" column is derived
# live from the backlog's blockedOn fields.
_blocks_for() {  # <needle>  → comma list of lane ids whose blockedOn contains needle
  _all | jq -r --arg n "$1" '[.[] | select((.blockedOn // "") | test($n)) | .id] | join(", ") | if .=="" then "-" else . end'
}

O1="Apple Developer enrollment (\$99, ~1–2 days) — gates Lane K signing/notarization"
O2="Demo script (the specific session/song, beat by beat) — gates B skills"
O3="FMS verdict (score the 8 seeds; PASS = ≥2/8 demo-worthy AND ≥4/8 directionally right)"
O4="Accounts & secrets (Cloudflare R2 + Supabase function secret + commercial API key; rotate the bundled key; register Stable Audio)"
O5="Arena harvest hour (judge ~38 candidates; pick what fits the script)"
O6="Housekeeping (½ day): fast-forward main; commit/discard stray files; prune stale worktrees; tag+park the SA3 LoRA branch"

# Open owner-merge PRs (best-effort; empty if gh is unavailable / not authed).
owner_prs=""
if command -v gh >/dev/null 2>&1; then
  owner_prs="$(gh pr list --state open --label needs-owner-merge --limit 100 \
    --json number,title,url,labels \
    -q '.[] | "| #\(.number) | \(.title) | \([.labels[].name] | map(select(startswith("program:") or .=="review-flagged")) | join(", ")) | \(.url) |"' 2>/dev/null || true)"
fi

tmp="$(mktemp)"
{
  echo "# First-Stranger Program — Status board"
  echo ""
  echo "_Auto-generated by \`scripts/first-stranger/status.sh\` at $NOW. Do not hand-edit — it is regenerated each loop cycle. Source of truth: \`docs/first-stranger-program/backlog.jsonl\`._"
  echo ""
  echo "| status | count |"
  echo "|---|---|"
  for s in ready in_progress awaiting-owner blocked needs-human gap-closed done; do
    c="$(_count "$s")"; [ "${c:-0}" = "0" ] && continue
    echo "| $s | $c |"
  done
  echo ""

  echo "## ▶ Ready now (the loop will work these)"
  echo ""
  echo "| id | lane | title | class | blockedOn |"
  echo "|---|---|---|---|---|"
  _rows ready
  echo ""

  echo "## 🔒 Awaiting your merge (gated + reviewed PRs)"
  echo ""
  if [ -n "$owner_prs" ]; then
    echo "| PR | title | labels | url |"
    echo "|---|---|---|---|"
    printf '%s\n' "$owner_prs"
  else
    echo "_No open \`needs-owner-merge\` PRs (or \`gh\` unavailable). Lanes currently marked awaiting-owner in the backlog:_"
    echo ""
    echo "| id | lane | title | class | blockedOn |"
    echo "|---|---|---|---|---|"
    _rows awaiting-owner
  fi
  echo ""

  echo "## ⛔ Blocked on you (clear the O-task, then flip the lane to \`ready\`)"
  echo ""
  echo "| id | lane | title | class | blockedOn |"
  echo "|---|---|---|---|---|"
  _rows blocked
  echo ""
  echo "### Owner critical path (O1–O6)"
  echo ""
  echo "| task | what it is | blocks lanes |"
  echo "|---|---|---|"
  echo "| O1 | $O1 | $(_blocks_for 'O1') |"
  echo "| O2 | $O2 | $(_blocks_for 'O2') |"
  echo "| O3 | $O3 | - |"
  echo "| O4 | $O4 | $(_blocks_for 'O4') |"
  echo "| O5 | $O5 | $(_blocks_for 'O5') |"
  echo "| O6 | $O6 | - |"
  echo "| hw | 2 machines + a live relay (S0 sizing spike) | $(_blocks_for 'owner-hardware') |"
  echo ""
  echo "> To unblock a lane once its O-task is done: \`AL_BACKLOG_JSONL=$PROG/backlog.jsonl scripts/auto-loop/discover.sh set-status <id> ready\`"
  echo ""

  done_rows="$(_rows done)"
  if [ -n "$done_rows" ]; then
    echo "## ✅ Done"
    echo ""
    echo "| id | lane | title | class | blockedOn |"
    echo "|---|---|---|---|---|"
    printf '%s\n' "$done_rows"
    echo ""
  fi

  echo "---"
  echo "_Kill switch: \`touch docs/auto-loop/STOP\` (or \`docs/first-stranger-program/STOP\`) halts the loop. Ledger: \`docs/first-stranger-program/LEDGER.md\`._"
} > "$tmp"

mv "$tmp" "$OUT"
echo "wrote $OUT"
