"""Scoreboard renderer (FMS lyrics-bench I1). Pure: summaries in → markdown out.

Numbers, hashes, and model ids only — corpus text never reaches the committed doc.
Until calibration/TRUSTED_METRICS.json exists the board states loudly that only
the deterministic columns mean anything.
"""
from __future__ import annotations

from typing import List, Optional

_COLS = ("exact", "topk", "syl_fit", "rhyme_fit", "rhyme_perfect",
         "constrained_fit")
_GRANS = ("word", "rhyme", "span", "line")


def _pct(v) -> str:
    return f"{100 * v:.1f}" if isinstance(v, (int, float)) else "—"


def render(entries: List[dict], trusted: Optional[dict]) -> str:
    lines = ["# FMS lyrics-bench — scoreboard", ""]
    if trusted:
        lines.append("Calibrated: trusted metric per granularity — " + ", ".join(
            f"**{g}: {t['metric']}** (owner agreement {t.get('agreement')})"
            for g, t in sorted(trusted.items())))
    else:
        lines.append("**UNCALIBRATED** — deterministic columns only; judged metrics "
                     "are untrusted until the owner blind-calibration round (I2).")
    lines.append("")

    ordered = sorted(entries, key=lambda e: (e["slice"],
                                             e["summary"]["arm"]["name"],
                                             e.get("runDir", "")))
    for gran in _GRANS:
        rows = [e for e in ordered if gran in e["summary"]["metrics"]]
        if not rows:
            continue
        lines.append(f"## {gran}")
        lines.append("")
        header = ["arm", "slice", "n"] + list(_COLS) + ["empty", "run"]
        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "---|" * len(header))
        for e in rows:
            s = e["summary"]
            m = s["metrics"][gran]
            row = [s["arm"]["name"], e["slice"], str(m.get("n", "—"))]
            row += [_pct(m.get(c)) for c in _COLS]
            row += [str(s.get("emptyCandidates", "—")), e.get("runDir", "")]
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

    lines.append("*Values are percentages of items (multi_depth excluded from the "
                 "table; see per-run summaries). Regenerated by `bench_cli.py "
                 "scoreboard` — do not hand-edit.*")
    return "\n".join(lines) + "\n"
