"""Scoreboard renderer (FMS lyrics-bench I1). Pure: summaries in → markdown out.

Numbers, hashes, and model ids only — corpus text never reaches the committed doc.
Until calibration/TRUSTED_METRICS.json exists the board states loudly that only
the deterministic columns mean anything.
"""
from __future__ import annotations

from typing import List, Optional

_COLS = ("exact", "topk", "syl_fit", "rhyme_fit", "rhyme_perfect",
         "constrained_fit")
_GRANS = ("word", "rhyme", "span", "line")


def _pct(v) -> str:
    return f"{100 * v:.1f}" if isinstance(v, (int, float)) else "—"


def _depth(v) -> str:
    """multi_depth is a syllable COUNT, not a rate — rendering it as a
    percentage (180.0) would read as a number nobody can interpret."""
    return f"{v:.2f}" if isinstance(v, (int, float)) else "—"


def _metric_row(name: str, slice_: str, m: dict, empty, run: str) -> str:
    cells = [name, slice_, str(m.get("n", "—"))]
    cells += [_pct(m.get(c)) for c in _COLS]
    cells += [_depth(m.get("multi_depth")), str(empty), run]
    return "| " + " | ".join(cells) + " |"


def _header() -> List[str]:
    head = ["arm", "slice", "n"] + list(_COLS) + ["multi_depth", "empty", "run"]
    return ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]


def _fame_block(entries: List[dict], gran: str) -> List[str]:
    """Low-fame first, because that is the bucket where exact-match cannot be
    memorization; the high bucket follows as the diagnostic, and the difference
    between them IS the memorization estimate."""
    have = [e for e in entries
            if (e["summary"].get("metricsByFame") or {}).get("low", {}).get(gran)
            or (e["summary"].get("metricsByFame") or {}).get("high", {}).get(gran)]
    if not have:
        return []
    out: List[str] = []
    for bucket, label in (("low", "low-fame — THE HEADLINE"),
                          ("high", "high-fame — memorization diagnostic")):
        rows = [e for e in have
                if (e["summary"]["metricsByFame"].get(bucket) or {}).get(gran)]
        if not rows:
            continue
        out += [f"**{gran} · {label}**", ""] + _header()
        for e in rows:
            s = e["summary"]
            out.append(_metric_row(s["arm"]["name"], e["slice"],
                                   s["metricsByFame"][bucket][gran],
                                   s.get("emptyCandidates", "—"),
                                   e.get("runDir", "")))
        out.append("")
    out += ["*A gain visible only in the high-fame block is memorization, not "
            "writing — compare the two `exact` columns before believing an arm.*",
            ""]
    return out


def render(entries: List[dict], trusted: Optional[dict]) -> str:
    lines = ["# FMS lyrics-bench — scoreboard", ""]
    if trusted:
        lines.append("Calibrated: trusted metric per granularity — " + ", ".join(
            f"**{g}: {t['metric']}** (owner agreement {t.get('agreement')})"
            for g, t in sorted(trusted.items())))
    else:
        lines.append("**UNCALIBRATED** — deterministic columns only; judged metrics "
                     "are untrusted until the owner blind-calibration round (I2).")
    lines.append("")

    ordered = sorted(entries, key=lambda e: (e["slice"],
                                             e["summary"]["arm"]["name"],
                                             e.get("runDir", "")))
    for gran in _GRANS:
        rows = [e for e in ordered if gran in e["summary"]["metrics"]]
        if not rows:
            continue
        lines.append(f"## {gran}")
        lines.append("")
        lines += _fame_block(rows, gran)
        lines += ["**all items (pooled)**", ""] + _header()
        for e in rows:
            s = e["summary"]
            lines.append(_metric_row(s["arm"]["name"], e["slice"],
                                     s["metrics"][gran],
                                     s.get("emptyCandidates", "—"),
                                     e.get("runDir", "")))
        lines.append("")

    lines.append("*Values are percentages of items, except `multi_depth`, which is "
                 "a mean rhyme depth in syllables — an arm that raises `exact` "
                 "while dropping `multi_depth` is drifting toward generic. "
                 "Regenerated by `bench_cli.py scoreboard` — do not hand-edit.*")
    return "\n".join(lines) + "\n"
