// GENERATED by `npm run flywheel` from eval/knowledge/cards.jsonl — do not edit by hand.
// The validated technique cards the product bundle ships, retrieved + injected at
// inference (retrieve.ts). Regenerate by running the flywheel after it validates cards.
import type { TechniqueCard } from "./card";

export const VALIDATED_CARDS: TechniqueCard[] = [
  {
    "id": "card_7a0163",
    "source": "distill",
    "skill_name": "lo-fi hip-hop production recipe",
    "task_type": "prompt_craft",
    "genre_context": [
      "lo-fi hip-hop",
      "lo-fi",
      "boom-bap",
      "hip-hop",
      "lofi"
    ],
    "producer_intent": "A terse generative prompt renders only what it names. Spelling out the canonical lo-fi elements + production character makes the generated loop sound like the brief instead of a bare drum loop.",
    "when": "Generating a lo-fi / hip-hop beat or loop from a text prompt.",
    "recipe": {
      "kind": "prompt",
      "guidance": "name every element + the production character: dusty boom-bap drums, warm Rhodes/electric-piano chords, mellow sub bass, plus vinyl crackle, tape saturation and MPC swing; reference 90s SP-1200/J Dilla; comma-separated tags with BPM + key"
    },
    "evidence": [
      {
        "brief": "lo-fi hip-hop beat, dusty boom-bap drums, warm Rhodes chords, mellow sub bass",
        "metric": "clap_brief",
        "withScore": 0.495,
        "withoutScore": 0.336,
        "delta": 0.159
      }
    ],
    "confidence": 0.8,
    "status": "validated"
  },
  {
    "id": "card_1shcyuj",
    "source": "distill",
    "skill_name": "Dusty Boom-Bap Drums with MPC Swing",
    "task_type": "prompt_craft",
    "genre_context": [
      "lo-fi hip-hop"
    ],
    "producer_intent": "Add authentic boom-bap drum texture with the signature swing of an MPC sampler to make the beat feel loose and vintage.",
    "when": "when generating the drum loop via prompt",
    "recipe": {
      "kind": "prompt",
      "guidance": "dusty boom-bap drums, MPC swing"
    },
    "evidence": [
      {
        "brief": "lo-fi-hip-hop seed42",
        "metric": "clap_brief",
        "withScore": 0.114,
        "withoutScore": 0.082,
        "delta": 0.032
      },
      {
        "brief": "lo-fi-hip-hop seed7",
        "metric": "clap_brief",
        "withScore": 0.104,
        "withoutScore": 0.079,
        "delta": 0.024999999999999994
      }
    ],
    "confidence": 0.614,
    "status": "validated"
  },
  {
    "id": "card_135uggz",
    "source": "distill",
    "skill_name": "Mellow Sub Bass with Vintage Tape Saturation",
    "task_type": "prompt_craft",
    "genre_context": [
      "lo-fi hip-hop"
    ],
    "producer_intent": "Add a gentle, round sub bass that sits underneath the beat, colored with vintage tape warmth for that lo-fi character.",
    "when": "when generating the bass line via prompt",
    "recipe": {
      "kind": "prompt",
      "guidance": "mellow sub bass, vintage tape saturation"
    },
    "evidence": [
      {
        "brief": "lo-fi-hip-hop seed42",
        "metric": "clap_brief",
        "withScore": 0.122,
        "withoutScore": 0.082,
        "delta": 0.039999999999999994
      },
      {
        "brief": "lo-fi-hip-hop seed7",
        "metric": "clap_brief",
        "withScore": 0.135,
        "withoutScore": 0.079,
        "delta": 0.05600000000000001
      }
    ],
    "confidence": 0.692,
    "status": "validated"
  }
];
