// GENERATED by `npm run flywheel` from eval/knowledge/cards.jsonl — do not edit by hand.
// The validated technique cards the product bundle ships, retrieved + injected at
// inference (retrieve.ts). Regenerate by running the flywheel after it validates cards.
import type { TechniqueCard } from "./card";

export const VALIDATED_CARDS: TechniqueCard[] = [
  {
    "id": "card_7a0163",
    "source": "distill",
    "skill_name": "lo-fi hip-hop production recipe",
    "task_type": "prompt_craft",
    "genre_context": [
      "lo-fi hip-hop",
      "lo-fi",
      "boom-bap",
      "hip-hop",
      "lofi"
    ],
    "producer_intent": "A terse generative prompt renders only what it names. Spelling out the canonical lo-fi elements + production character makes the generated loop sound like the brief instead of a bare drum loop.",
    "when": "Generating a lo-fi / hip-hop beat or loop from a text prompt.",
    "recipe": {
      "kind": "prompt",
      "guidance": "name every element + the production character: dusty boom-bap drums, warm Rhodes/electric-piano chords, mellow sub bass, plus vinyl crackle, tape saturation and MPC swing; reference 90s SP-1200/J Dilla; comma-separated tags with BPM + key"
    },
    "evidence": [
      {
        "brief": "lo-fi hip-hop beat, dusty boom-bap drums, warm Rhodes chords, mellow sub bass",
        "metric": "clap_brief",
        "withScore": 0.495,
        "withoutScore": 0.336,
        "delta": 0.159
      }
    ],
    "confidence": 0.8,
    "status": "validated"
  },
  {
    "id": "card_1shcyuj",
    "source": "distill",
    "skill_name": "Dusty Boom-Bap Drums with MPC Swing",
    "task_type": "prompt_craft",
    "genre_context": [
      "lo-fi hip-hop"
    ],
    "producer_intent": "Add authentic boom-bap drum texture with the signature swing of an MPC sampler to make the beat feel loose and vintage.",
    "when": "when generating the drum loop via prompt",
    "recipe": {
      "kind": "prompt",
      "guidance": "dusty boom-bap drums, MPC swing"
    },
    "evidence": [
      {
        "brief": "lo-fi-hip-hop seed42",
        "metric": "clap_brief",
        "withScore": 0.114,
        "withoutScore": 0.082,
        "delta": 0.032
      },
      {
        "brief": "lo-fi-hip-hop seed7",
        "metric": "clap_brief",
        "withScore": 0.104,
        "withoutScore": 0.079,
        "delta": 0.024999999999999994
      }
    ],
    "confidence": 0.614,
    "status": "validated"
  },
  {
    "id": "card_135uggz",
    "source": "distill",
    "skill_name": "Mellow Sub Bass with Vintage Tape Saturation",
    "task_type": "prompt_craft",
    "genre_context": [
      "lo-fi hip-hop"
    ],
    "producer_intent": "Add a gentle, round sub bass that sits underneath the beat, colored with vintage tape warmth for that lo-fi character.",
    "when": "when generating the bass line via prompt",
    "recipe": {
      "kind": "prompt",
      "guidance": "mellow sub bass, vintage tape saturation"
    },
    "evidence": [
      {
        "brief": "lo-fi-hip-hop seed42",
        "metric": "clap_brief",
        "withScore": 0.122,
        "withoutScore": 0.082,
        "delta": 0.039999999999999994
      },
      {
        "brief": "lo-fi-hip-hop seed7",
        "metric": "clap_brief",
        "withScore": 0.135,
        "withoutScore": 0.079,
        "delta": 0.05600000000000001
      }
    ],
    "confidence": 0.692,
    "status": "validated"
  },
  {
    "id": "card_12sr5ye",
    "source": "distill",
    "skill_name": "Boom-bap drum pattern (kick/snare/8th-hats)",
    "task_type": "drum_programming",
    "genre_context": [
      "boom-bap",
      "lo-fi hip-hop",
      "hip-hop"
    ],
    "producer_intent": "the classic boom-bap skeleton — kick on the 1 and the 'and' of 3, snare on the 2 & 4, hats on every 8th",
    "when": "programming a boom-bap or lo-fi hip-hop drum pattern from scratch",
    "recipe": {
      "kind": "recipe",
      "commands": [
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 36,
            "start": 0,
            "length": 0.25,
            "velocity": 110
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 36,
            "start": 2.5,
            "length": 0.25,
            "velocity": 110
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 38,
            "start": 1,
            "length": 0.25,
            "velocity": 100
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 38,
            "start": 3,
            "length": 0.25,
            "velocity": 100
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 42,
            "start": 0,
            "length": 0.25,
            "velocity": 80
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 42,
            "start": 0.5,
            "length": 0.25,
            "velocity": 80
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 42,
            "start": 1,
            "length": 0.25,
            "velocity": 80
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 42,
            "start": 1.5,
            "length": 0.25,
            "velocity": 80
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 42,
            "start": 2,
            "length": 0.25,
            "velocity": 80
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 42,
            "start": 2.5,
            "length": 0.25,
            "velocity": 80
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 42,
            "start": 3,
            "length": 0.25,
            "velocity": 80
          }
        },
        {
          "command": "add_note",
          "args": {
            "clipId": "$drumClipId",
            "pitch": 42,
            "start": 3.5,
            "length": 0.25,
            "velocity": 80
          }
        }
      ]
    },
    "evidence": [
      {
        "brief": "lofi-85-Am",
        "metric": "technique_conformance",
        "withScore": 1,
        "withoutScore": 0,
        "delta": 1
      },
      {
        "brief": "dark-70-Cm",
        "metric": "technique_conformance",
        "withScore": 1,
        "withoutScore": 0,
        "delta": 1
      }
    ],
    "confidence": 0.75,
    "status": "conformant"
  },
  {
    "id": "card_ayxwyv",
    "source": "distill",
    "skill_name": "MPC swing on the hats (~0.58)",
    "task_type": "drum_programming",
    "genre_context": [
      "boom-bap",
      "lo-fi hip-hop",
      "hip-hop",
      "neo-soul"
    ],
    "producer_intent": "push the off-beat 8ths late for that drunk MPC/boom-bap swing instead of a stiff straight grid",
    "when": "the hats/drums feel too straight and need a swung, off-grid groove",
    "recipe": {
      "kind": "recipe",
      "commands": [
        {
          "command": "quantize_notes",
          "args": {
            "clipId": "$hatsClipId",
            "division": 0.5,
            "strength": 1,
            "swing": 0.58
          }
        }
      ]
    },
    "evidence": [
      {
        "brief": "lofi-85-Am",
        "metric": "technique_conformance",
        "withScore": 1,
        "withoutScore": 0,
        "delta": 1
      },
      {
        "brief": "dark-70-Cm",
        "metric": "technique_conformance",
        "withScore": 1,
        "withoutScore": 0,
        "delta": 1
      }
    ],
    "confidence": 0.75,
    "status": "conformant"
  },
  {
    "id": "card_1mrax2f",
    "source": "distill",
    "skill_name": "Humanize the keys (subtle timing + velocity)",
    "task_type": "arrangement",
    "genre_context": [
      "lo-fi hip-hop",
      "neo-soul",
      "boom-bap"
    ],
    "producer_intent": "a small seeded timing + velocity jitter so a programmed Rhodes/keys part breathes instead of sounding robotic",
    "when": "a programmed keys/chord part sounds too quantized / robotic",
    "recipe": {
      "kind": "recipe",
      "commands": [
        {
          "command": "humanize_notes",
          "args": {
            "clipId": "$keysClipId",
            "timing": 0.2,
            "velocity": 0.3,
            "seed": 42
          }
        }
      ]
    },
    "evidence": [
      {
        "brief": "lofi-85-Am",
        "metric": "technique_conformance",
        "withScore": 1,
        "withoutScore": 0,
        "delta": 1
      },
      {
        "brief": "dark-70-Cm",
        "metric": "technique_conformance",
        "withScore": 1,
        "withoutScore": 0,
        "delta": 1
      }
    ],
    "confidence": 0.75,
    "status": "conformant"
  },
  {
    "id": "card_7oekwz",
    "source": "distill",
    "skill_name": "Filter-open automation over the intro",
    "task_type": "mixing",
    "genre_context": [
      "lo-fi hip-hop",
      "house",
      "electronic"
    ],
    "producer_intent": "automate the EQ/filter opening up over the bars for movement, instead of a single static setting",
    "when": "an intro/build needs movement — open the filter up over time",
    "recipe": {
      "kind": "recipe",
      "commands": [
        {
          "command": "add_automation_point",
          "args": {
            "trackId": "$keysTrackId",
            "pluginIndex": "$keysFilterPluginIndex",
            "paramIndex": "$keysFilterParamIndex",
            "time": 0,
            "value": 0.2
          }
        },
        {
          "command": "add_automation_point",
          "args": {
            "trackId": "$keysTrackId",
            "pluginIndex": "$keysFilterPluginIndex",
            "paramIndex": "$keysFilterParamIndex",
            "time": 4,
            "value": 0.9
          }
        }
      ]
    },
    "evidence": [
      {
        "brief": "lofi-85-Am",
        "metric": "technique_conformance",
        "withScore": 1,
        "withoutScore": 0,
        "delta": 1
      },
      {
        "brief": "dark-70-Cm",
        "metric": "technique_conformance",
        "withScore": 1,
        "withoutScore": 0,
        "delta": 1
      }
    ],
    "confidence": 0.75,
    "status": "conformant"
  },
  {
    "id": "card_ip4mp1",
    "source": "distill",
    "skill_name": "Shared reverb on a send bus",
    "task_type": "mixing",
    "genre_context": [
      "lo-fi hip-hop",
      "neo-soul",
      "ambient"
    ],
    "producer_intent": "send the keys to ONE shared reverb return for depth, instead of a reverb inserted on every track",
    "when": "the mix needs depth / space — a shared reverb the tracks send to",
    "recipe": {
      "kind": "recipe",
      "commands": [
        {
          "command": "create_bus",
          "args": {
            "name": "Reverb"
          }
        },
        {
          "command": "add_send",
          "args": {
            "trackId": "$keysTrackId",
            "bus": "$busNumber",
            "db": -12
          }
        }
      ]
    },
    "evidence": [
      {
        "brief": "lofi-85-Am",
        "metric": "technique_conformance",
        "withScore": 1,
        "withoutScore": 0,
        "delta": 1
      },
      {
        "brief": "dark-70-Cm",
        "metric": "technique_conformance",
        "withScore": 1,
        "withoutScore": 0,
        "delta": 1
      }
    ],
    "confidence": 0.75,
    "status": "conformant"
  }
];
