import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { inventory, type Inputs } from "./inventory";
import { mineSkill } from "./mine";
import { hash } from "./corpus";
import { MiningError } from "./types";

export function checkDeterminism(inputs: Inputs): void {
  const first = inventory(inputs);
  const second = inventory(inputs);
  if (JSON.stringify(first) !== JSON.stringify(second)) throw new MiningError("Inventory regeneration is nondeterministic");
  const recorded = readFileSync(join(inputs.root, "docs/skills/measurements.json"), "utf8");
  if (recorded !== JSON.stringify(first.data, null, 2) + "\n") throw new MiningError("Regenerated measurements differ from recorded measurements");
  const byId = new Map(first.train.map(row => [row.id, row]));
  const hashes: Record<string, string> = {};
  first.selected.forEach((group, index) => {
    const rows = group.rows.map(id => {
      const row = byId.get(id);
      if (!row) throw new MiningError(`Missing provenance: ${id}`);
      return row;
    });
    const skill = mineSkill(group, rows, index + 1);
    const serialized = JSON.stringify(skill, null, 2) + "\n";
    const saved = readFileSync(join(inputs.root, "skills", `${skill.id}.json`), "utf8");
    if (serialized !== saved) throw new MiningError(`Skill regeneration differs: ${skill.id}`);
    for (const example of skill.examples) if (!rows.some(row => row.utterance === example)) throw new MiningError(`Nonverbatim example: ${skill.id}`);
    hashes[skill.id] = hash(saved);
  });
  writeFileSync(join(inputs.root, "docs/skills/determinism.json"), JSON.stringify({
    status: "passed", inventory: "Two independent reads identical to recorded measurements", skills: "All 40 regenerated byte-for-byte, including provenance and verbatim examples",
    frozenSelectionIdsSha256: first.data.frozenSelectionIdsSha256, skillHashes: hashes,
  }, null, 2) + "\n");
}
