// Producer knowledge base — the "why/when" the command catalog (commands.ts) lacks.
// The catalog tells Moshi's brain WHAT each command does; these cards tell it, in
// plain producer terms, WHY/WHEN to reach for a control and what a param really means.
// A few relevant cards are retrieved per turn and injected next to the catalog by
// buildSystemPrompt() (brainCore.ts).
//
// The store is committed JSONL (one card per line) held as a string constant so it is
// bundle-safe under BOTH Vite (the app) AND tsx (the offline brain scripts) with zero
// bundler magic — no ?raw import, no fs read. Retrieval is deterministic tag/keyword
// match behind a swappable `retrieveCards` seam (mirrors the lyric style_corpus.retrieve
// posture: a lexical scorer now, a real embedding backend a parked upgrade behind the
// same seam). Cards are OWNER/ASSISTANT-authored — never auto-extracted (see
// docs/bench/FX_KB_PILOT.md for why VLM auto-extraction was a NO-GO).
//
// Schema note: `maps_to` is the control/param/command a card explains — the join key a
// future UI can use to surface the same card as an inline hint on the matching control.

export type KnowledgeCard = {
  /** Stable unique id — one card is one fact. */
  readonly id: string;
  /** Short human topic (for authoring/index; not shown to the model). */
  readonly topic: string;
  /** The control/param/command this card is about — the UI-hint join key. */
  readonly maps_to: string;
  /** What it does, in one layman sentence. */
  readonly plain: string;
  /** When to reach for it. */
  readonly when: string;
  /** Keyword tags — the primary retrieval signal. */
  readonly tags: readonly string[];
};

// ── the committed store (JSONL, one card per line) ────────────────────────────────
// Append a card = add a line. Keep it valid JSON with double-quoted keys/strings.
export const PRODUCER_KNOWLEDGE_JSONL = `
{"id":"song-key-in-scale-notes","topic":"Writing notes that are in key","maps_to":"add_note / set_key","plain":"The project carries a musical key (tonic + mode) that you can read from the snapshot as session.key; when you write a melody or bassline with add_note, pick pitches that belong to that key's scale instead of arbitrary semitones, or the part will sound wrong against everything else.","when":"adding melodic or bass notes, or before proposing a chord/melody idea.","tags":["key","scale","tonic","mode","melody","bass","add_note","set_key","in key","notes","pitch"]}
{"id":"scale-lock-is-ui-only","topic":"Scale lock does not apply to your commands","maps_to":"scale lock (piano roll)","plain":"Scale lock is a piano-roll INPUT AID for the person clicking: it snaps notes they draw or drag to the song key, and it deliberately does not touch add_note calls that come from you — so you must choose in-key pitches yourself, and you should never assume a pitch you sent was corrected.","when":"you are about to add notes and the producer has mentioned a key, or asks why your notes sound out of key.","tags":["scale","lock","key","snap","piano roll","add_note","in key","input aid","ui"]}
{"id":"scale-lock-never-rewrites","topic":"Turning scale lock on will not fix existing notes","maps_to":"scale lock (piano roll)","plain":"Scale lock only constrains a note as the producer draws it or drags it to a new pitch; it never sweeps the clip, so switching it on will not retune an existing part, and sliding a note sideways in time leaves its pitch alone even if that pitch is out of key.","when":"the producer turns on scale lock expecting an out-of-key part to be corrected.","tags":["scale","lock","existing","notes","rewrite","retune","key","piano roll"]}
{"id":"sa3-onset-steering","topic":"Opening energy fades across the clip","maps_to":"colors / neural steering","plain":"SA3 makes a stronger statement in the first ~1 second then settles; the steering/colors nudge the model's 'brain' in a direction, and a time-scheduled steer can KEEP that opening energy going across the whole clip instead of letting it fade.","when":"the generation starts strong then thins out and you want it to stay full.","tags":["energy","intro","opening","arrangement","steering","colors","fade","settles"]}
{"id":"reimagine-noise-amount","topic":"How far a re-imagine departs from your beat","maps_to":"nl / init_noise_level (re-imagine)","plain":"The re-imagine 'noise' is how much of YOUR original beat to keep vs how much Moshi reinvents — low (<=0.5) keeps your groove and stays clean over long clips, high (>=0.7) reinvents more but can make each section restart its intro.","when":"deciding how far to push a re-imagine, or if a long re-imagine pulses every few bars.","tags":["reimagine","noise","amount","nl","init_noise_level","whole-clip","groove","pulse"]}
{"id":"warp-stretch-clip-bars","topic":"Fitting an imported loop to the grid","maps_to":"stretch_clip","plain":"stretch_clip time-stretches a wave clip (warp) to a target length in seconds or a bar count, so an imported loop locks to your project tempo instead of drifting out of sync.","when":"an imported loop doesn't line up with the grid, or you want it to fill an exact number of bars.","tags":["warp","stretch","stretch_clip","fit","bars","loop","tempo","grid","imported"]}
{"id":"warp-detect-clip-bpm-confidence","topic":"How sure the BPM detector is","maps_to":"detect_clip_bpm","plain":"detect_clip_bpm estimates a wave clip's tempo (read-only) and comes back with a confidence alongside the BPM guess — low confidence usually means the take has a loose or ambiguous groove, so treat the number as a starting point, not gospel.","when":"you don't know a sample or loop's original tempo before warping it to the grid.","tags":["warp","bpm","detect","detect_clip_bpm","confidence","tempo","estimate"]}
{"id":"warp-drag-to-stretch","topic":"Dragging a loop's edge to fit bars","maps_to":"warp / drag-to-stretch (Inspector)","plain":"Holding Cmd and dragging a wave clip's edge, or using the Inspector's Fit-bars / 1/2x / 2x buttons, is the hands-on version of stretch_clip — it drives the same warp engine under the hood (the set_clip_warp toggle, which is UI-only and not agent-callable), and Detect can auto-lock a loop to the grid the instant warp turns on.","when":"you're eyeballing a loop against the grid instead of typing an exact bar count.","tags":["warp","drag","stretch","fit","bars","grid","inspector","detect","auto-lock","set_clip_warp"]}
{"id":"drum-pattern-lane-syntax","topic":"Writing a drum pattern in one shot","maps_to":"add_drum_pattern","plain":"add_drum_pattern lays a whole grid from lane strings in one undoable step — 'x' is a hit, 'X' is an accent (louder), '.' or '-' is a rest, and '|' is just a cosmetic bar divider; lanes are kick/snare/clap/hat/openhat/lowtom/midtom/crash, or a raw MIDI pitch for a custom pad.","when":"you want a whole pattern laid down from a description like kick on 1 and 3, snare on 2 and 4, instead of adding notes one at a time.","tags":["drums","drum_pattern","add_drum_pattern","pattern","kick","snare","hat","accent","rest","lane","syntax"]}
{"id":"drum-pattern-tiling","topic":"Short lanes repeating to fill the bar","maps_to":"add_drum_pattern (tiling)","plain":"a lane string shorter than the full step count tiles to fill it — writing a short dot-x pattern for hats gives steady 8ths across the whole bar without typing every step, as long as the short lane divides evenly into stepsPerBar times bars.","when":"you want a busier lane, like hats, without spelling out every repeat by hand.","tags":["drums","add_drum_pattern","tile","tiling","hat","repeat","pattern","shorthand","stepsperbar"]}
{"id":"drum-sketch-beatbox","topic":"Turning a beatboxed take into an editable drum clip","maps_to":"sketch_beatbox","plain":"sketch_beatbox transduces a recorded beatbox WAV into an editable drum clip at a known BPM, snapping kick/snare/hat hits onto a 16th grid so you get real MIDI drum notes instead of raw audio.","when":"you beatboxed a rough drum idea and want it as editable notes instead of manually programming the grid.","tags":["drums","sketch_beatbox","beatbox","transduce","record","voice","kick","snare","hat","16th"]}
{"id":"lyrics-build-skeleton-from-clip","topic":"Turning a mumbled take into a syllable grid","maps_to":"build_skeleton_from_clip","plain":"build_skeleton_from_clip listens to a hummed or mumbled wave take and turns it into an editable rhythmic flow skeleton — a syllable grid plus stress pattern, no words yet — on the clip's track; you confirm the grid, then finishing the gaps writes the actual words.","when":"you've hummed or mumbled a vocal flow before you have lyrics, and want the rhythm captured before writing to it.","tags":["lyrics","skeleton","build_skeleton_from_clip","mumble","flow","syllable","grid","stress","rhythm"]}
{"id":"lyrics-complete-lyrics","topic":"Filling every gap in a lyric sheet at once","maps_to":"complete_lyrics","plain":"complete_lyrics fills every remaining gap across a track's whole lyric sheet in one call, returning ranked proposals per line that are already syllable- and rhyme-checked against your grid.","when":"most of the sheet is still gaps and you want a full first pass instead of filling line by line.","tags":["lyrics","complete_lyrics","gap","fill","proposals","syllable","rhyme","sheet"]}
{"id":"lyrics-fill-lyric-gap","topic":"Filling just one line's gaps","maps_to":"fill_lyric_gap","plain":"fill_lyric_gap generates ranked proposals for a single lyric line's gaps without touching the rest of the sheet — useful once most lines are written and only one still has a hole.","when":"one specific line needs finishing and you don't want complete_lyrics to touch lines you already like.","tags":["lyrics","fill_lyric_gap","gap","line","proposals","one-line"]}
{"id":"lyrics-suggest-next-line","topic":"Getting a ghost line to continue the flow","maps_to":"suggest_next_line","plain":"suggest_next_line proposes a brand-new line after a given index — a ghost line for when you've run out of ideas, rather than a gap-fill of something you already typed.","when":"you're stuck for what comes next after a line, not fixing a specific gap.","tags":["lyrics","suggest_next_line","ghost","next","line","suggestion","stuck"]}
{"id":"lyrics-analyze-lyrics","topic":"Checking a written line's flow without generating","maps_to":"analyze_lyrics","plain":"analyze_lyrics is read-only — it grades every finalized line's syllable count, stress contour and rhyme match against its group anchor with no LLM call, the same check the generator itself uses to pass or fail a line.","when":"you typed a line by hand and want to know if it actually hits the syllable and rhyme target before moving on.","tags":["lyrics","analyze_lyrics","syllable","stress","rhyme","flow","check","phonology"]}
{"id":"lyrics-get-rhymes","topic":"Looking up rhymes for a specific word","maps_to":"get_rhymes","plain":"get_rhymes runs a phoneme-based rhyme search, perfect or slant, filterable by syllable count, with no LLM involved — it's a dictionary and phonology lookup, so it's instant and exact rather than a generated guess.","when":"you already have the line and just need rhyme options for one word to fit the count.","tags":["lyrics","get_rhymes","rhyme","phonology","perfect","slant","word","dictionary"]}
{"id":"generative-create-render-layer-modes","topic":"Re-imagine vs transform on a render layer","maps_to":"create_render_layer","plain":"create_render_layer attaches a generative layer to any clip — wave, MIDI, or drum, with MIDI/drum auto-bounced to audio first; the adapter picks the mode — re-imagine keeps roughly your version and reinvents around it, transform pushes the sound toward a different target instrument or timbre.","when":"deciding whether to reshape what's already there (re-imagine) or turn it into something else entirely (transform).","tags":["generative","create_render_layer","reimagine","transform","adapter","layer","clip"]}
{"id":"generative-compile-render","topic":"Turning a loose instruction into a real render","maps_to":"compile_render","plain":"compile_render takes a loose instruction like \\"make it lo-fi\\" or \\"as a violin\\" and auto-picks re-imagine vs transform, filling in prompt, colours and noise or target and strength for you — it honestly declines corrective asks like fix or tune, or vocal requests it can't actually do.","when":"you'd rather describe the vibe in plain language than manually set render params.","tags":["generative","compile_render","instruction","auto","prompt","colours","target","strength"]}
{"id":"generative-set-render-param","topic":"Dialing in a render layer's parameters","maps_to":"set_render_param","plain":"set_render_param tunes a render layer directly — prompt, noise level and seed for re-imagine; target and strength for transform; or coverage for how a long clip gets covered, tiling a short loop versus stitching separate windows.","when":"you already have a layer and want to adjust it rather than re-describe it from scratch.","tags":["generative","set_render_param","prompt","noise","seed","target","strength","coverage"]}
{"id":"generative-keep-reimagine-dial","topic":"The 0-100 keep-vs-re-imagine dial versus raw noise","maps_to":"nl (0-100 keep <-> re-imagine dial)","plain":"the re-imagine drawer's 0-100 keep-to-re-imagine dial is the friendly face of set_render_param's raw nl noise level (0-1) — it's ASTD-clamped below the point where a render collapses into mush, and Lab mode is the only way to push nl past that clamp into the raw, un-clamped range.","when":"explaining why the dial tops out before it feels totally wild, or why Lab mode unlocks a higher setting.","tags":["generative","nl","dial","keep","reimagine","astd","clamp","lab","noise"]}
{"id":"mixer-track-volume-pan","topic":"Balancing a track in the mix","maps_to":"set_track_volume / set_track_pan","plain":"set_track_volume sets a track's fader in dB and set_track_pan moves it left or right, from -1 full left to 1 full right — the most basic mix moves before reaching for any plugin.","when":"one track is too loud, too quiet, or sits too centered against the others.","tags":["mixer","volume","pan","set_track_volume","set_track_pan","fader","balance","mix"]}
{"id":"mixer-sends-returns","topic":"Sharing one reverb or delay across several tracks","maps_to":"create_bus / add_send / set_send_level","plain":"create_bus makes an aux or return track, like a shared reverb or delay; add_send routes a post-fader send from any track into it at a level in dB, and set_send_level adjusts that amount later — cheaper and more cohesive than loading the same effect on every track.","when":"several tracks need the same space or ambience and duplicating the plugin per-track would be wasteful and inconsistent.","tags":["mixer","sends","returns","bus","create_bus","add_send","set_send_level","reverb","delay","aux"]}
{"id":"mixer-master-and-remove-send","topic":"The master bus and pulling a track out of a send","maps_to":"set_master_volume / set_master_pan / remove_send","plain":"set_master_volume and set_master_pan control the final master fader and pan the whole mix passes through, separate from any single track; remove_send takes a track back out of a bus if it no longer needs that shared reverb or delay.","when":"the overall mix is too loud or quiet, or one track was sent to a bus by mistake.","tags":["mixer","master","set_master_volume","set_master_pan","remove_send","bus"]}
{"id":"vst3-load-plugin","topic":"Adding a hosted VST3/AU plugin to a track","maps_to":"load_plugin","plain":"load_plugin adds a scanned VST3 or AU plugin, by pluginId from list_plugins, onto a track's chain at a given position — this is how a real hosted synth or effect, not one of Mosh's built-ins, gets onto a track.","when":"you want a specific third-party synth or effect rather than one of Mosh's built-ins.","tags":["vst3","au","plugin","load_plugin","host","chain"]}
{"id":"vst3-chain-order","topic":"Why plugin order in the chain matters","maps_to":"reorder_plugin","plain":"reorder_plugin moves a plugin to a new position in a track's signal chain — order matters, since an EQ before a compressor reacts differently than one placed after it, so reordering is how you fix a chain that's right in concept but wrong in sequence.","when":"the same plugins are loaded but the sound isn't right until you change what processes first.","tags":["vst3","plugin","reorder_plugin","chain","order","signal","sequence"]}
{"id":"vst3-open-editor","topic":"Opening a plugin's real interface","maps_to":"open_plugin_editor","plain":"open_plugin_editor pops out a plugin's native editor window — set_plugin_param only reaches raw 0-1 parameter values, so for anything with a real interface, like browsing presets or drawing an envelope, you open the editor instead.","when":"a plugin's actual window, presets, or visual controls are needed, not just nudging one parameter number.","tags":["vst3","plugin","open_plugin_editor","editor","gui","preset","native"]}
{"id":"recording-arm-track","topic":"Arming a track before you record","maps_to":"arm_track","plain":"arm_track arms or disarms a track's input for recording — a track has to be armed before set_transport's record action actually captures anything onto it.","when":"you're about to record and nothing is being captured, or you want to make sure only the right track picks up input.","tags":["recording","arm_track","armed","input","record","takes"]}
{"id":"recording-input-monitor","topic":"Hearing your input while armed","maps_to":"set_input_monitor","plain":"set_input_monitor controls whether an armed track's live input is audible through the mix — off, automatic, or on — so you can hear yourself while recording without it depending on playback state alone.","when":"you can't hear what you're about to record, or you're hearing it doubled during playback.","tags":["recording","set_input_monitor","monitor","input","armed","hear"]}
{"id":"recording-take-lanes","topic":"Multiple takes stacked on one clip","maps_to":"list_takes / set_current_take","plain":"recording over an existing clip stacks a new take lane instead of overwriting it; list_takes shows what's stacked and set_current_take switches which lane actually plays — nothing is lost until you commit to one.","when":"you recorded several passes at the same spot and want to compare or switch between them.","tags":["recording","takes","list_takes","set_current_take","lane","stack","compare"]}
{"id":"recording-keep-take","topic":"Committing to one take and discarding the rest","maps_to":"keep_take","plain":"keep_take keeps the currently-selected take lane on a clip and permanently removes the other stacked takes — the cleanup step once you've picked a favorite via set_current_take.","when":"you're done comparing takes and want to stop carrying the unused ones around.","tags":["recording","keep_take","take","commit","cleanup","lane"]}
{"id":"recording-stop-recording","topic":"Stopping a recording and landing the take","maps_to":"stop_recording","plain":"stop_recording ends the current recording and lands the take as a clip, or with discardRecordings throws it away — the explicit stop for when you're not just relying on the transport's own stop.","when":"you want to end a take, or discard it, without necessarily stopping the whole transport by other means.","tags":["recording","stop_recording","stop","land","take","discard"]}
{"id":"generative-render-vs-accept","topic":"Running a render vs landing it","maps_to":"render_layer / accept_render","plain":"render_layer actually runs the generative job on a clip's layer; accept_render commits a finished render — for wave clips it auto-applies in place already so accept is a no-op there, but for MIDI/drum clips accept_render is the step that lands the hidden render as a real clip.","when":"confused why a MIDI re-imagine needs an extra accept step that a wave clip doesn't.","tags":["generative","render_layer","accept_render","commit","apply","midi","wave"]}
{"id":"mixer-solo-mute","topic":"Soloing to listen vs muting to silence","maps_to":"set_track_solo / set_track_mute","plain":"set_track_solo silences every OTHER track so you can hear one track in isolation without changing the mix; set_track_mute silences that ONE track instead — solo is a listening tool, mute is an arranging decision.","when":"you want to hear one track alone for a moment, versus actually deciding a track shouldn't be part of the mix right now.","tags":["mixer","solo","mute","set_track_solo","set_track_mute","isolate","listen"]}
{"id":"mixer-bus-send-numbering","topic":"Routing a send by the bus's number, not its name","maps_to":"add_send / set_send_level","plain":"add_send and set_send_level route by the bus's NUMBER from the snapshot's buses array, not by typing the bus's name — create_bus hands back that number when it makes the return track, so read the number from there rather than guessing it.","when":"a send call errors or lands on the wrong return because the bus was addressed by name instead of number.","tags":["mixer","bus","buses","add_send","set_send_level","create_bus","number","route"]}
{"id":"plugin-param-normalized-range","topic":"Plugin parameters are always 0-1, never real units","maps_to":"set_plugin_param","plain":"set_plugin_param always takes a normalized value between 0 and 1, never the plugin's real-world unit like Hz, dB or milliseconds — a filter cutoff at 0.5 is the middle of ITS range, not 500 Hz; open_plugin_editor is how you dial in an actual real-world number.","when":"a parameter tweak did nothing sensible because a raw Hz or dB number was sent instead of a normalized value.","tags":["plugin","set_plugin_param","normalized","range","parameter","value"]}
{"id":"plugin-bypass-vs-remove","topic":"Bypassing a plugin for A/B vs removing it","maps_to":"bypass_plugin / remove_plugin","plain":"bypass_plugin flips a plugin off while leaving it in the chain, so you can compare it against the dry signal and flip it back on; remove_plugin deletes it from the chain entirely — reach for bypass when comparing, remove when it's not coming back.","when":"you're deciding whether a plugin is actually helping and want an instant compare, not a permanent decision.","tags":["plugin","bypass_plugin","remove_plugin","bypass","remove","compare","chain"]}
{"id":"plugin-builtin-vs-hosted","topic":"Mosh's own effects/instruments vs a scanned third-party plugin","maps_to":"load_builtin / load_plugin","plain":"load_builtin adds one of Mosh's own built-in effects or instruments — no scanning or plugin id required; load_plugin instead loads a scanned third-party VST3 or AU by its plugin id, for something specific Mosh doesn't ship natively.","when":"deciding between something quick and always-available versus a specific named plugin you already have installed.","tags":["plugin","load_builtin","load_plugin","builtin","instrument","effect","vst3","au","third-party"]}
{"id":"recording-arm-vs-monitor","topic":"Being armed doesn't mean you can hear yourself","maps_to":"arm_track / set_input_monitor","plain":"arm_track only enables capture on a track's input — it says nothing about whether you HEAR that input; set_input_monitor is the separate off/automatic/on switch for whether an armed track's live input is actually audible through the mix.","when":"a track is armed and ready to record but you can't hear your own input, or you're hearing it doubled during playback.","tags":["recording","arm_track","set_input_monitor","armed","monitor","hear","capture"]}
{"id":"recording-discard-vs-keep","topic":"Throwing out what you just recorded vs picking a favorite take","maps_to":"stop_recording / keep_take","plain":"stop_recording with discardRecordings set throws away what was JUST captured before it ever becomes a take lane; keep_take is a later, different moment — it runs after several takes are already stacked and you've picked a favorite with set_current_take, clearing out the rest.","when":"a take was clearly bad the instant you stopped, versus several takes are stacked and you're ready to commit to one.","tags":["recording","stop_recording","keep_take","discard","take","takes"]}
{"id":"multiplayer-session-basics","topic":"Working on a project with someone else at the same time","maps_to":"multiplayer session (Create/Join)","plain":"a multiplayer session lets a second person join the same project live over a persistent room code — creating a room starts a shared session, and joining one REPLACES whatever local project is currently open, so Mosh confirms before a join actually swaps the project out.","when":"you and a collaborator want to work on the same session together instead of trading files back and forth.","tags":["multiplayer","session","room","code","collaborator","relay","join"]}
{"id":"history-undo-scope","topic":"Undo covers every command, not just note edits","maps_to":"undo / redo","plain":"undo and redo walk the SAME history as every other MoshOps command — a track rename, a plugin load, a send you just added, all revert with undo exactly like a note edit does, because every mutation in Mosh goes through one shared undo system.","when":"you're not sure whether undo will actually catch a non-note change like adding a plugin or a track.","tags":["history","undo","redo","undoable","mutation","revert"]}
{"id":"session-save-habit","topic":"Saving locks in progress before a risky move","maps_to":"save","plain":"save writes the whole session to disk immediately, not on some timer — it's the one deliberate checkpoint you control, worth reaching for right before a plugin load, an accept on a render, or anything else that could crash mid-operation.","when":"you're about to do something that touches a plugin or a big render and want a safety checkpoint first.","tags":["session","save","checkpoint","disk","crash","safety"]}
{"id":"transport-loop-region","topic":"Looping a section for practice or a repeated listen","maps_to":"set_transport (loop)","plain":"set_transport's loop flag turns on loop playback at the CURRENT loop region, so setting it true and starting playback repeats the same span over and over — useful for dialing in a part or an effect without constantly re-seeking back to the start of a section.","when":"you keep manually seeking back to the same spot to hear it again instead of letting playback repeat it.","tags":["transport","set_transport","loop","looping","region","repeat","playback"]}
{"id":"transport-seek-actions","topic":"Jumping to the start/end vs an exact position","maps_to":"set_transport (action)","plain":"set_transport's action covers the transport buttons — to_start and to_end jump to the edges of the session, while play/toggle/stop/record control playback state; for an exact spot instead of an edge, pass position in seconds rather than one of the action strings.","when":"you want to jump to the very beginning or end, or seek to a specific timestamp instead of pressing play from wherever the playhead sits.","tags":["transport","set_transport","seek","to_start","to_end","action","playhead"]}
{"id":"drum-kit-track-type-overlap","topic":"create_track/set_track_type already load the kit — load_drum_kit is for recovery","maps_to":"load_drum_kit / set_track_type","plain":"creating a track with type drum, or calling set_track_type to drum on an existing one, already loads the sampler and drum kit for you — load_drum_kit exists separately for re-loading that same kit onto a track that lost it, or was never switched to drum type in the first place.","when":"a drum track somehow has no kit loaded, or you're building a track from scratch and unsure which command actually puts sounds on the pads.","tags":["drums","drum_kit","load_drum_kit","set_track_type","create_track","sampler"]}
{"id":"assign-sample-melodic-order","topic":"A track with an instrument already loaded is left alone","maps_to":"assign_sample / add_drum_pattern","plain":"assign_sample in melodic mode puts a pitched sampler like an 808 onto a track; once that track already carries an instrument, add_drum_pattern's auto-track setup leaves it untouched instead of overwriting it with a fresh drum kit — only an instrument-less track gets auto-kitted.","when":"you assigned a melodic 808 sample to a track and then laid a drum pattern, worried it might replace your sampler with a generic kit.","tags":["assign_sample","add_drum_pattern","melodic","instrument","untouched","auto-kit"]}
{"id":"warp-length-vs-bars-arg","topic":"stretch_clip's two ways to say a target","maps_to":"stretch_clip","plain":"stretch_clip takes EITHER a length in seconds or a bar count, never both — bars is the one to reach for when a loop should fill an exact musical span regardless of tempo, while length is for a known exact duration in seconds.","when":"deciding whether to give stretch_clip a bar count or a seconds value for the target length.","tags":["warp","stretch_clip","length","seconds","target","duration"]}
{"id":"warp-detect-before-stretch","topic":"Checking a tempo guess before you commit to a stretch","maps_to":"detect_clip_bpm / stretch_clip","plain":"running detect_clip_bpm before stretch_clip shows you the estimate first, so an obviously-off guess on an unfamiliar loop gets caught before a warp is applied instead of after.","when":"you're about to time-stretch a loop you don't know the original tempo of and want a read-only check first.","tags":["warp","detect_clip_bpm","stretch_clip","estimate","tempo","pair"]}
{"id":"mistake-instrument-silences-track-audio","topic":"An instrument on a track silences any audio clip sharing it","maps_to":"instrument on a track (silences audio clips)","plain":"once a track has an instrument loaded — via set_track_type to drum, load_drum_kit, or a synth from load_builtin/load_plugin — that instrument's output overwrites the track's audio buffer, so any wave clip sitting on the SAME track goes completely silent; a re-imagine's generated audio has to live on a separate, dedicated track for exactly this reason.","when":"an audio clip that was working fine suddenly plays silent right after an instrument got added to its track.","tags":["instrument","silence","silent","overwrite","mistake","buffer","hidden-render"]}
{"id":"mistake-reorder-changes-indices","topic":"A chain index shifts after you reorder a plugin","maps_to":"reorder_plugin","plain":"reorder_plugin moves a plugin to a new position, which shifts every other plugin's index in that track's chain — an index read from the snapshot before the reorder is stale immediately after, so re-check the chain before addressing another plugin by index.","when":"a follow-up set_plugin_param, bypass_plugin, or open_plugin_editor call lands on the wrong plugin right after a reorder.","tags":["plugin","reorder_plugin","index","chain","position","stale"]}
{"id":"clip-gain-trim-one-clip","topic":"Trimming one clip's own level without touching the track fader","maps_to":"set_clip_gain","plain":"set_clip_gain nudges a single audio clip's own gain in dB, clamped -48 to +24 — it only works on a wave clip, not MIDI or drum, and it's separate from the track's overall fader (set_track_volume), so it doesn't move any other clip sharing that track.","when":"one particular clip sits louder or quieter than the clips around it and only that clip's own level needs trimming, not the whole track's fader.","tags":["clip","gain","set_clip_gain","trim","level","db","wave","audio","per-clip"]}
{"id":"clip-mute-one-clip","topic":"Silencing a single clip without muting the whole track","maps_to":"set_clip_mute","plain":"set_clip_mute mutes or unmutes just one clip, any clip type, while every other clip on that track and the track itself keep playing normally — set_track_mute is the separate command for silencing an entire track.","when":"one specific clip, like an alternate take or an experimental section, needs to go quiet without touching anything else on its track.","tags":["clip","mute","unmute","set_clip_mute","silence","one-clip","alternate","take"]}
{"id":"transport-tempo-time-signature-range","topic":"Changing the whole song's tempo and meter","maps_to":"set_tempo / set_time_signature","plain":"set_tempo sets the project's single tempo point in BPM, clamped 20-999; set_time_signature sets the numerator and a denominator that must be a power of two from 1 to 32 (1, 2, 4, 8, 16, 32) — both describe the WHOLE project's tempo map, not one clip, so they don't time-stretch anything by themselves.","when":"you want to change the whole song's speed or meter, not fit one imported loop to the existing grid (that's stretch_clip).","tags":["tempo","meter","set_tempo","set_time_signature","numerator","denominator","project","song","clamp"]}
{"id":"mixer-remove-rename-bus","topic":"Deleting or relabeling an aux/return bus","maps_to":"remove_bus / rename_bus","plain":"remove_bus deletes an aux/return bus and automatically sweeps every track's send pointing at it, so nothing dangling is left behind; rename_bus just relabels an existing bus in place, by its bus NUMBER — the same numbering create_bus/add_send/set_send_level use — without touching its sends or level.","when":"a bus you created turns out empty and unneeded, or its label no longer matches what it's actually being used for.","tags":["mixer","bus","remove_bus","rename_bus","delete","relabel","aux","return","cleanup"]}
{"id":"mixer-track-output-routing","topic":"Sending a track's output somewhere other than the master","maps_to":"set_track_output / list_track_outputs","plain":"set_track_output points a track's output away from the master bus — into another track as an informal submix, out to a specific hardware device by id, or back with output:\\"default\\" to undo either; list_track_outputs is the read-only lookup for which hardware outs and track destinations actually exist before you pick one.","when":"several tracks need to funnel into one shared destination for further processing, or a track needs to come out of a different physical output than the rest of the mix.","tags":["mixer","routing","route","set_track_output","list_track_outputs","submix","device","hardware","output","destination"]}
{"id":"export-stems-vs-mixdown","topic":"Exporting individual tracks vs the final mix","maps_to":"export_stems / export_audio","plain":"export_stems renders every track to its OWN audio file in a directory, all sharing one common zero point so they stay in sync when reloaded elsewhere; export_audio instead renders the whole mix down to a single file — reach for stems when a mix or mastering engineer needs the individual tracks, not just the final bounce.","when":"sending the project to a collaborator or engineer who needs to remix or master the individual tracks rather than just listen to the final mix.","tags":["export","export_stems","export_audio","stems","mixdown","bounce","render","tracks","file"]}
{"id":"automation-write-mode-captures","topic":"Recording automation by performing the tweak","maps_to":"set_track_automation_mode (write)","plain":"set_track_automation_mode arms a track's automation recording — switch it to write and moving ANY plugin parameter on that track from then on drops a point onto that parameter's curve at the playhead's current position, so the curve gets built by literally performing the move instead of calling add_automation_point by hand for every change.","when":"you want a parameter to change over time and would rather record the move live than type out exact points.","tags":["automation","write","set_track_automation_mode","record","capture","live","param","mode","arm"]}
{"id":"automation-mode-meanings","topic":"What each automation record mode actually does","maps_to":"set_track_automation_mode (read/touch/latch/write)","plain":"set_track_automation_mode's four modes are read (the default — plays back whatever curve already exists and records nothing), write (captures a point on every parameter change), and touch/latch — both are accepted and round-trip on the track, but in v0 neither actually behaves any differently from read yet.","when":"picking which automation mode to arm, or wondering why touch or latch doesn't seem to be doing anything special.","tags":["automation","mode","read","touch","latch","write","set_track_automation_mode","inert","behave"]}
{"id":"automation-write-curve-bulk","topic":"Authoring a whole automation curve in one step","maps_to":"write_automation_curve","plain":"write_automation_curve lays down an entire automation curve for one plugin parameter in ONE undoable call from a list of time/value points, instead of dropping points one at a time or recording a live write pass — apply replace, the default, clears whatever curve already covered that time span first, apply merge only adds the new points alongside what's there.","when":"you already know the exact curve shape you want and would rather describe it as a list of points than perform it live or add each point by hand.","tags":["automation","write_automation_curve","bulk","curve","points","replace","merge","author","shape"]}
{"id":"automation-point-add-vs-clear","topic":"Nudging one point vs wiping the whole curve","maps_to":"add_automation_point / clear_automation","plain":"add_automation_point drops a single point onto a plugin parameter's curve at an exact time and value — the one-at-a-time alternative to write mode or write_automation_curve; clear_automation instead wipes every point on that parameter at once, a clean reset for a messy curve instead of removing points one by one.","when":"you want to nudge in one exact point without recording a whole pass, or a curve got messy and wiping it clean beats deleting points individually.","tags":["automation","add_automation_point","clear_automation","point","wipe","reset","manual","messy"]}
{"id":"clip-reverse-playback","topic":"Playing a clip's audio backwards","maps_to":"set_clip_reverse","plain":"set_clip_reverse flips a wave clip's audio to play backwards in place — it reverses the audio content itself, not the clip's position or length on the timeline.","when":"you want a clip's audio playing backwards, like a reversed cymbal swell or a reversed vocal chop.","tags":["clip","reverse","set_clip_reverse","backwards","wave","playback","flip","swell"]}
{"id":"clip-crossfade-overlap-only","topic":"Auto-crossfade only matters where clips overlap","maps_to":"set_clip_crossfade","plain":"set_clip_crossfade turns on an automatic crossfade for a wave clip, but it's only actually audible where that clip OVERLAPS a neighboring clip on the SAME track — enabling it on a clip that doesn't overlap anything produces no audible change at all.","when":"two clips butt up against or overlap each other on a track and the edit between them clicks or pops.","tags":["clip","crossfade","set_clip_crossfade","overlap","neighbor","edit","click","pop","seam"]}
{"id":"clip-normalize-nondestructive","topic":"Leveling a clip's peak without touching the file","maps_to":"normalize_clip","plain":"normalize_clip sets a wave clip's gain so its loudest sample peak lands at a target dB, 0 dB by default — it's non-destructive, computing and setting the same kind of gain set_clip_gain would rather than rewriting the audio file itself.","when":"a clip's peak sits noticeably quieter or louder than the clips around it and you want it leveled to a target peak instead of eyeballing a gainDb value.","tags":["clip","normalize","normalize_clip","gain","peak","db","non-destructive","level"]}
`.trim();

function parseKnowledge(jsonl: string): KnowledgeCard[] {
  const out: KnowledgeCard[] = [];
  for (const raw of jsonl.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("//")) continue;
    const o = JSON.parse(line) as KnowledgeCard;
    out.push({
      id: String(o.id),
      topic: String(o.topic),
      maps_to: String(o.maps_to),
      plain: String(o.plain),
      when: String(o.when),
      tags: Array.isArray(o.tags) ? o.tags.map(String) : [],
    });
  }
  return out;
}

/** The parsed producer-knowledge store. */
export const PRODUCER_KNOWLEDGE: readonly KnowledgeCard[] = parseKnowledge(PRODUCER_KNOWLEDGE_JSONL);

// ── deterministic tag/keyword retrieval (swappable seam) ──────────────────────────

const TOKEN_RE = /[a-z0-9]+/g;
// Very common / low-signal words carry no "which control" signal — exclude them.
const STOP = new Set([
  "the", "a", "an", "and", "or", "but", "to", "of", "in", "on", "at", "for", "with",
  "i", "me", "my", "you", "your", "it", "its", "is", "are", "be", "am", "as", "so",
  "that", "this", "do", "does", "did", "how", "should", "can", "could", "would",
  "will", "if", "then", "than", "out", "up", "down", "more", "less", "not", "no",
  "yes", "just", "now", "when", "why", "what", "some", "any", "get", "got",
]);

function tokenize(text: string): string[] {
  const out: string[] = [];
  for (const m of (text || "").toLowerCase().matchAll(TOKEN_RE)) {
    const t = m[0];
    if (t.length >= 2 && !STOP.has(t)) out.push(t);
  }
  return out;
}

// A card's token → weight bag. Tags are the primary signal (3); topic/maps_to next
// (2); the prose (plain/when) lowest (1) so a producer's natural phrasing still hits.
function cardWeights(card: KnowledgeCard): Map<string, number> {
  const w = new Map<string, number>();
  const add = (text: string, weight: number) => {
    for (const t of tokenize(text)) if ((w.get(t) ?? 0) < weight) w.set(t, weight);
  };
  add(`${card.plain} ${card.when}`, 1);
  add(`${card.topic} ${card.maps_to}`, 2);
  add(card.tags.join(" "), 3);
  return w;
}

export type RetrieveOptions = {
  /** Max cards to return (default 3). */
  readonly limit?: number;
  /** The pool to score against (default: the committed store). */
  readonly cards?: readonly KnowledgeCard[];
};

/** The few cards most relevant to `query`, by weighted tag/keyword overlap.
 *  Deterministic: rank by score, ties break by id. Zero-overlap cards are dropped
 *  (an irrelevant card in the prompt is worse than none — the style_corpus principle). */
export function retrieveCards(query: string, opts: RetrieveOptions = {}): KnowledgeCard[] {
  const cards = opts.cards ?? PRODUCER_KNOWLEDGE;
  const limit = opts.limit ?? 3;
  const qTokens = Array.from(new Set(tokenize(query)));
  if (qTokens.length === 0) return [];
  const scored = cards
    .map((card) => {
      const w = cardWeights(card);
      let score = 0;
      for (const t of qTokens) score += w.get(t) ?? 0;
      return { card, score };
    })
    .filter((s) => s.score > 0);
  scored.sort((a, b) => b.score - a.score || a.card.id.localeCompare(b.card.id));
  return scored.slice(0, limit).map((s) => s.card);
}

/** Render retrieved cards into a compact system-prompt block. Empty ⇒ "" (so the
 *  prompt is byte-unchanged when nothing is relevant). */
export function knowledgePromptSection(cards: readonly KnowledgeCard[]): string {
  if (cards.length === 0) return "";
  return [
    "Producer knowledge — plain-language notes on the controls this request may touch. Use them to choose and explain moves; speak them in your own voice, never quote verbatim.",
    ...cards.map((c) => `- ${c.maps_to}: ${c.plain} (when: ${c.when})`),
  ].join("\n");
}
